// The client event contract is deliberately explicit. A new event must be
// named here before it can be stored; this keeps analytics useful and stops a
// future UI change from accidentally turning the event store into a keystroke
// or content archive.
export const CLIENT_ANALYTICS_EVENT_NAMES = Object.freeze([
  'page.viewed', 'landing.viewed', 'pricing.viewed', 'signup.started', 'signup.completed', 'signup.failed', 'signin.viewed', 'signin.succeeded', 'signin.failed', 'google.signin', 'email.verification.started', 'email.verification.completed', 'email.verification.failed', 'password.reset.started', 'password.reset.completed',
  'onboarding.step.viewed', 'onboarding.step.saved', 'onboarding.abandoned', 'onboarding.completed',
  'dashboard.opened', 'dashboard.delivery.list.loaded', 'dashboard.delivery.list.partial_failure', 'dashboard.search.used', 'dashboard.filter.used', 'dashboard.view.changed', 'dashboard.delivery.opened', 'dashboard.draft.resumed', 'dashboard.delivery.archived', 'dashboard.delivery.restored', 'dashboard.delivery.deleted', 'dashboard.link.copied', 'dashboard.whatsapp.opened', 'dashboard.library.opened', 'dashboard.portfolio.opened', 'dashboard.settings.opened',
  'delivery.creation.started', 'delivery.creation.step.viewed', 'delivery.creation.step.completed', 'delivery.creation.back', 'delivery.brief.saved', 'delivery.format.viewed', 'delivery.format.selected', 'delivery.format.changed', 'delivery.review.opened', 'delivery.review.approved', 'delivery.caption.edited', 'delivery.caption.regenerated', 'delivery.photo.reordered', 'delivery.section.changed', 'delivery.layout.changed', 'delivery.typography.changed', 'delivery.colour.changed', 'delivery.preview.opened', 'delivery.publish.succeeded', 'delivery.publish.failed', 'delivery.link.copied', 'delivery.qr.downloaded', 'delivery.email.sent', 'delivery.whatsapp.opened',
  'upload.started', 'upload.completed', 'upload.failed', 'upload.retried', 'upload.cancelled', 'upload.library.selected',
  'format.recommendation.accepted', 'format.recommendation.rejected',
  'music.catalogue.opened', 'music.preview.started', 'music.preview.completed', 'music.track.selected', 'music.track.replaced', 'music.uploaded', 'music.failed',
  'narration.enabled', 'narration.disabled', 'narration.voice.selected', 'narration.requested', 'narration.completed', 'narration.failed', 'narration.played', 'narration.paused', 'narration.muted', 'narration.resumed', 'narration.timing.failed', 'audio.loading.failed',
  'client.delivery.opened', 'client.delivery.load.failed', 'client.pin.shown', 'client.pin.attempted', 'client.pin.succeeded', 'client.pin.failed', 'client.preloader.started', 'client.preloader.completed', 'client.preloader.failed', 'client.first.photo.shown', 'client.experience.started', 'client.experience.completed', 'client.format.opened', 'client.chapter.opened', 'client.album.page.turned', 'client.canvas.moved', 'client.photo.reveal.advanced', 'client.gallery.opened', 'client.photo.opened', 'client.caption.viewed', 'client.like.added', 'client.like.removed', 'client.photo.download.requested', 'client.photo.download.started', 'client.photo.download.failed', 'client.download.all.started', 'client.download.all.partial_failed', 'client.share.opened', 'client.music.started', 'client.music.paused', 'client.music.resumed', 'client.music.ended', 'client.music.failed', 'client.narration.started', 'client.narration.paused', 'client.narration.muted', 'client.narration.resumed', 'client.narration.failed', 'client.link.expired', 'client.link.revoked',
  'volume.job.created', 'volume.recipient.list.uploaded', 'volume.recipient.added', 'volume.recipient.edited', 'volume.recipient.deleted', 'volume.auto_assignment.started', 'volume.auto_assignment.completed', 'volume.files.unmatched', 'volume.assignment.manual', 'volume.csv.exported', 'volume.recipient.link.published', 'volume.access.code.requested', 'volume.access.code.verified', 'volume.access.code.failed', 'volume.recipient.gallery.opened', 'volume.recipient.photo.opened', 'volume.recipient.download.started', 'volume.recipient.download.failed',
  'portfolio.editor.opened', 'portfolio.saved', 'portfolio.direction.requested', 'portfolio.direction.completed', 'portfolio.direction.failed', 'portfolio.published', 'portfolio.unpublished', 'portfolio.viewed', 'portfolio.filter.used', 'portfolio.project.opened', 'portfolio.whatsapp.clicked', 'portfolio.instagram.clicked', 'portfolio.enquiry.clicked',
  'api.request.completed', 'api.request.failed', 'javascript.error', 'media.image.failed', 'media.audio.failed', 'download.failed', 'worker.timeout', 'core.web_vitals', 'page.scrolled', 'session.engaged', 'analytics.consent.granted'
]);

export const CLIENT_ANALYTICS_EVENT_SET = new Set(CLIENT_ANALYTICS_EVENT_NAMES);
