import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, Check, ChevronLeft, ChevronRight, Images, List, Volume2, VolumeX, X } from 'lucide-react';
import { createPortal } from 'react-dom';
import { useDialogFocus } from '../useDialogFocus.js';
import { useClosingGallery } from '../../utils/useClosingGallery.js';
import { useSmoothSoundtrackLoop } from '../../utils/smoothSoundtrackLoop.js';
import { presentationSettings, numberLabel } from '../../utils/deliveryPresentation.js';
import { Photo } from '../PublicDesign.jsx';
import { CollectionGallery, ImageWaiting, PhotoCard, PresentationShell, usePresentation, useReadyPhotos } from './PresentationShell.jsx';
import './CollectionViewers.css';

import './AlbumViewer.css';
function AlbumPage({ page, ready, onViewed, onPhoto, children }) {
  const end = useRef(null);
  const { galleryUnlocked: visibleEnd, closingRef } = useClosingGallery(`${page.id}:${ready.key}`);
  const ref = React.useCallback(node => { end.current = node; closingRef(node); }, [closingRef]);
  useEffect(() => { if (ready.ready && visibleEnd) onViewed(page.id); }, [ready.ready, visibleEnd, page.id, onViewed]);
  return <article className={`pv-album-page layout-${page.layout}`} aria-busy={!ready.ready}><div className="pv-album-page-heading"><span className="pv-eyebrow">{page.label}</span>{page.heading && <h2>{page.heading}</h2>}{page.note && <p>{page.note}</p>}</div><div className="pv-album-photos">{ready.photos.map((photo, index) => <PhotoCard key={photo.assetId} photo={photo} index={page.indices?.[index] ?? index} onOpen={onPhoto} caption={!['cover', 'closing'].includes(page.id)} eager />)}</div>{children}<div className="pv-spread-end" ref={ref}>— {page.label} —</div></article>;
}
export function AlbumViewer({ delivery = {}, galleryProps, demo = false }) {
  const context = usePresentation(delivery, galleryProps, demo), settings = presentationSettings(delivery, context.photos.map(photo => photo.assetId));
  const pages = useMemo(() => [{ id: 'cover', layout: 'single', label: 'THE ALBUM', heading: delivery.title, note: delivery.creativeDirection?.openingLine, assetIds: [context.opening?.assetId] }, ...settings.spreads.map((spread, index) => ({ ...spread, id: `spread:${spread.id}`, label: `SPREAD ${numberLabel(index + 1)}`, indices: spread.assetIds.map(id => context.photos.findIndex(photo => photo.assetId === id)) })), { id: 'closing', layout: 'single', label: 'THE COMPLETE COLLECTION', heading: delivery.creativeDirection?.closingLine, assetIds: [context.closing?.assetId] }], [delivery, context.photos, context.opening, context.closing, JSON.stringify(settings.spreads)]);
  const [skipped, setSkipped] = useState([]);
  const [pageIndex, setPageIndex] = useState(0), [visited, setVisited] = useState([]), [gallery, setGallery] = useState(null), [overview, setOverview] = useState(false), [resume, setResume] = useState(null), [music, setMusic] = useState('off'), [direction, setDirection] = useState(1);
  const reduced = useReducedMotion(), pageTop = useRef(null), overviewRef = useRef(null), touch = useRef(null), audio = useRef(null);
  useSmoothSoundtrackLoop(audio, delivery.soundtrack?.url || '');
  useDialogFocus(overview, overviewRef, () => setOverview(false));
  const storageKey = `veylo-album:${context.identity}`;
  useEffect(() => { setPageIndex(0); setVisited([]); setSkipped([]); setGallery(null); setResume(null); try { const saved = JSON.parse(sessionStorage.getItem(storageKey) || 'null'); if (saved && Array.isArray(saved.visited) && Number.isInteger(saved.page) && saved.page > 0 && saved.page < pages.length) setResume(saved); } catch { /* Storage is optional. */ } }, [storageKey]);
  const mark = React.useCallback(id => setVisited(current => current.includes(id) ? current : [...current, id]), []);
  useEffect(() => { if (!visited.length) return; try { sessionStorage.setItem(storageKey, JSON.stringify({ page: pageIndex, visited, skipped })); } catch { /* Storage is optional. */ } }, [storageKey, pageIndex, visited, skipped]);
  const unlocked = pages.filter(page => page.id !== 'cover').every(page => visited.includes(page.id));
  const navigate = next => { const clamped = Math.max(0, Math.min(pages.length - 1, next)); setDirection(clamped >= pageIndex ? 1 : -1); setPageIndex(clamped); setOverview(false); requestAnimationFrame(() => { pageTop.current?.scrollIntoView({ behavior: 'auto', block: 'start' }); pageTop.current?.focus({ preventScroll: true }); }); };
  useEffect(() => { const key = event => { if (gallery || overview || event.target.closest('input,textarea,select,button')) return; if (event.key === 'ArrowRight') { event.preventDefault(); navigate(pageIndex + 1); } if (event.key === 'ArrowLeft') { event.preventDefault(); navigate(pageIndex - 1); } }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [pageIndex, gallery, overview, pages.length]);
  const requestedPage = pages[pageIndex], requested = requestedPage.assetIds.map(id => context.all.find(photo => photo.assetId === id)).filter(Boolean), neighbours = pages[pageIndex + 1]?.assetIds.map(id => context.all.find(photo => photo.assetId === id)) || [];
  const readiness = useReadyPhotos(requested, [...neighbours, ...pages[pageIndex - 1]?.assetIds.map(id => context.all.find(photo => photo.assetId === id)) || []]);
  const [displayed, setDisplayed] = useState(null);
  useEffect(() => { if (readiness.ready) setDisplayed({ page: requestedPage, photos: readiness.photos }); }, [readiness.ready, readiness.loadedKey, requestedPage.id]);
  const page = displayed?.page || requestedPage;
  const pageReady = { ...readiness, photos: displayed?.photos || requested.map(photo => ({ ...photo, url: photo.thumbnailUrl || photo.url })), ready: readiness.ready && (!displayed || displayed.page.id === requestedPage.id) };
  const play = async () => { if (!audio.current) return; if (!audio.current.paused) { audio.current.pause(); setMusic('off'); return; } setMusic('loading'); try { await audio.current.play(); setMusic('on'); } catch { setMusic('failed'); } };
  const nextUnread = pages.findIndex(item => item.id !== 'cover' && !visited.includes(item.id));
  const theme = { ...context.theme, ...(settings.paperTone === 'light' ? { '--fd-bg': '#f3eee4', '--fd-surface': '#e8e1d4', '--fd-text': '#29241c', '--fd-accent': '#86683e' } : settings.paperTone === 'dark' ? { '--fd-bg': '#151411', '--fd-surface': '#24221d', '--fd-text': '#f5eee2', '--fd-accent': '#d0b483' } : {}) };
  return <PresentationShell delivery={delivery} format="Album" theme={theme} onGallery={unlocked ? () => setGallery('all') : undefined} className="pv-album" hideSoundtrack>
    {delivery.soundtrack?.url && <audio ref={audio} src={delivery.soundtrack.url} preload="none" onError={() => setMusic('failed')} />}
    <main className="pv-main"><nav className="pv-album-toolbar"><button onClick={() => setOverview(true)}><List size={18} />Pages</button><span>{numberLabel(pageIndex + 1)} / {numberLabel(pages.length)}</span>{delivery.soundtrack?.url && <button onClick={play}>{music === 'on' ? <Volume2 size={18} /> : <VolumeX size={18} />}{music === 'loading' ? 'Loading music' : music === 'failed' ? 'Retry music' : music === 'on' ? 'Sound on' : 'Sound off'}</button>}</nav>
      {resume && pageIndex === 0 && <div className="pv-album-resume"><p>You stopped at page {resume.page + 1}.</p><button onClick={() => { setVisited(resume.visited.filter(id => pages.some(page => page.id === id))); setSkipped((resume.skipped || []).filter(id => pages.some(page => page.id === id))); navigate(resume.page); setResume(null); }}>Continue reading<ArrowRight size={17} /></button><button onClick={() => setResume(null)}>Start from the cover</button></div>}
      <div tabIndex={-1} ref={pageTop} className="pv-album-stage" onTouchStart={event => { const point = event.touches[0]; touch.current = { x: point.clientX, y: point.clientY }; }} onTouchEnd={event => { const start = touch.current, point = event.changedTouches[0]; if (start && Math.abs(point.clientX - start.x) > 65 && Math.abs(point.clientX - start.x) > Math.abs(point.clientY - start.y) * 1.5 && !event.target.closest('button')) navigate(pageIndex + (point.clientX < start.x ? 1 : -1)); touch.current = null; }}><AnimatePresence mode="wait" initial={false}><motion.div key={page.id} initial={reduced ? false : { opacity: 0, x: direction * 28 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: reduced ? 0 : direction * -20 }} transition={{ duration: reduced ? 0 : .2 }}><AlbumPage page={page} ready={pageReady} onViewed={mark} onPhoto={photo => setGallery(photo.assetId)}>{page.id === 'cover' && <button onClick={() => { navigate(1); if (music === 'off') void play(); }}>Open album<ArrowRight size={18} /></button>}{page.id === 'closing' && <div className="pv-album-closing-actions">{unlocked ? <button onClick={() => setGallery('all')}><Images size={18} />Open full gallery</button> : nextUnread >= 0 && <button onClick={() => navigate(nextUnread)}>Read an unviewed spread<ArrowRight size={18} /></button>}<button onClick={() => { setVisited([]); setSkipped([]); setResume(null); try { sessionStorage.removeItem(storageKey); } catch { /* Storage is optional. */ } navigate(0); }}>Read again</button></div>}</AlbumPage></motion.div></AnimatePresence><ImageWaiting state={readiness} skipLabel="Skip this page" onSkip={() => { setSkipped(current => [...new Set([...current, requestedPage.id])]); mark(requestedPage.id); navigate(pageIndex + 1); }} /></div>
      <div className="pv-album-progress" role="progressbar" aria-label="Album progress" aria-valuemin={1} aria-valuemax={pages.length} aria-valuenow={pageIndex + 1}><motion.span animate={{ scaleX: (pageIndex + 1) / pages.length }} transition={{ duration: reduced ? 0 : .2 }} /></div>{pages.length <= 10 && <nav className="pv-album-page-numbers" aria-label="Album page navigation">{pages.map((item, at) => <button key={item.id} aria-label={`Open album page ${at + 1}`} aria-current={at === pageIndex ? 'page' : undefined} onClick={() => navigate(at)}>{numberLabel(at + 1)}</button>)}</nav>}<nav className="pv-album-navigation"><button disabled={pageIndex === 0} onClick={() => navigate(pageIndex - 1)}><ChevronLeft />Previous</button><span>{visited.filter(id => id !== 'cover').length} of {pages.length - 1} pages explored</span><button disabled={pageIndex === pages.length - 1} onClick={() => navigate(pageIndex + 1)}>Next<ChevronRight /></button></nav>
    </main> {createPortal(<AnimatePresence>{overview && <motion.div className="pv-focus-backdrop" style={theme} initial={reduced ? false : { opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: reduced ? 0 : .2 }}><motion.section initial={reduced ? false : { opacity: 0, scale: .98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .98 }} transition={{ duration: reduced ? 0 : .28 }} ref={overviewRef} role="dialog" aria-modal="true" aria-label="Album pages" className="pv-overview"><header><h2>Album pages</h2><button onClick={() => setOverview(false)} aria-label="Close pages"><X /></button></header>{pages.map((item, at) => <button key={item.id} onClick={() => navigate(at)}><Photo url={context.all.find(photo => photo.assetId === item.assetIds[0])?.thumbnailUrl || context.all.find(photo => photo.assetId === item.assetIds[0])?.url} alt="" /><span>{numberLabel(at + 1)}</span><span>{item.heading || item.label}</span>{skipped.includes(item.id) ? <small>Skipped</small> : visited.includes(item.id) && <Check size={16} />}</button>)}</motion.section></motion.div>}</AnimatePresence>, document.body)}{gallery && <CollectionGallery context={context} delivery={delivery} selection={gallery} singlePhoto={!unlocked} onClose={() => setGallery(null)} />}
  </PresentationShell>;
}

export default AlbumViewer;
