const frame = (url, direction) => ({ duration: 6.4, ...direction, url });

export const DEMO_PRESETS = [
  {
    id: 'sharon', label: 'Sharon · Studio', genre: 'Studio Portraits', title: 'Sharon’s Studio Session', clientName: 'Sharon Adeleke', studioName: 'Studio Lumière Lagos', occasion: 'Fashion portrait session · Victoria Island, Lagos',
    photographerBrief: 'Sharon came in for a fashion portrait session in a sculpted ivory suit against a cobalt set. The photographs should feel confident, stylish and true to her personality.',
    storySummary: 'Sharon, you came in with one strong look and made it completely your own. These are the moments we loved most from your session.',
    opening: { eyebrow: 'Studio Lumière presents', headline: 'Sharon, these portraits are all you.', copy: 'You stepped onto the cobalt set with a quiet confidence that carried through the entire session.', buttonLabel: 'See your story' },
    finale: { eyebrow: 'Sharon’s studio session', headline: 'Sharon, you made this look your own.', copy: 'Your finished portraits are ready. Take your time and enjoy every one of them.', buttonLabel: 'Open your gallery', textAnimation: 'blur_reveal' },
    soundtrack: { title: 'Studio 35mm · High-Fashion Lounge', audioUrl: '/audio/soundtrack-3.mp3' },
    theme: { accentColor: '#d9c8b5', secondaryColor: '#101419', glowColor: 'rgba(217, 200, 181, 0.28)' },
    photos: [
      frame('/veylo/show/sharon-1.jpeg', { chapterTitle: 'YOU CAME READY', caption: 'Sharon, from the first photograph, you looked completely sure of yourself.', sceneLayout: 'cinema', transition: 'cut', typographyStyle: 'bold_banner', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'zoom_in', colorAccent: '#d9c8b5', visualAnalysis: { composition: 'Three-quarter portrait in sculpted ivory tailoring', palette: ['ivory', 'cobalt blue', 'black piping'], safeTextArea: 'lower left', mood: 'controlled and direct' } }),
      frame('/veylo/show/sharon-2.jpeg', { chapterTitle: 'YOUR OWN STYLE', caption: 'That small turn gave us one of the strongest portraits from your session.', sceneLayout: 'split', transition: 'slide_left', typographyStyle: 'editorial_quote', textAnimation: 'smooth_slide', textBackground: 'solid_dark', captionPosition: 'right', zoomEffect: 'pan_left', colorAccent: '#ebe2d8', visualAnalysis: { composition: 'Full-length walking profile across a cobalt set', palette: ['ivory', 'cobalt blue', 'black'], safeTextArea: 'left', mood: 'poised' } }),
      frame('/veylo/show/sharon-3.jpeg', { chapterTitle: 'A QUIETER SIDE', caption: 'We loved this quieter side of you—calm, thoughtful, and comfortable in the moment.', sceneLayout: 'poster', transition: 'fade', typographyStyle: 'minimal_clean', textAnimation: 'blur_reveal', textBackground: 'vogue_bordered', captionPosition: 'bottom', zoomEffect: 'zoom_out', colorAccent: '#b8a38d', visualAnalysis: { composition: 'Seated three-quarter portrait on a cobalt bench', palette: ['ivory', 'cobalt blue', 'soft grey'], safeTextArea: 'upper left', mood: 'quiet and self-possessed' } }),
      frame('/veylo/show/sharon-4.jpeg', { chapterTitle: 'ONE OF OUR FAVOURITES', caption: 'Sharon, we saved one of our favourite portraits from your session for the end.', sceneLayout: 'collage', transition: 'scale', typographyStyle: 'typewriter', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'pan_right', colorAccent: '#f0e6dc', visualAnalysis: { composition: 'Close three-quarter portrait with a hand at the shoulder line', palette: ['ivory', 'ink blue', 'black piping'], safeTextArea: 'lower right', mood: 'finished and precise' } })
    ]
  },
  {
    id: 'lora', label: 'Lora · Birthday', genre: 'Birthday Portraits', title: 'Lora’s Birthday Story', clientName: 'Lora', studioName: 'Birthday Portraits · Lagos', occasion: 'A birthday portrait session',
    photographerBrief: 'Lora’s birthday portrait session in an emerald dress against a warm orange backdrop. The cake, the gift, and her changing expressions bring out both the playful and quieter sides of the celebration.',
    storySummary: 'Lora, this birthday session had everything we wanted to remember: the green dress, the cake, the gift, and a smile that changed every frame.',
    opening: { eyebrow: 'Lora’s birthday portraits', headline: 'Lora, this birthday looks good on you.', copy: 'You brought the green dress and a smile that made the whole room feel lighter.', buttonLabel: 'See your birthday story', hint: 'Sound on. Tap either side when you want to move.' },
    finale: { eyebrow: 'Lora’s birthday', headline: 'Happy birthday, Lora.', copy: 'Keep this smile close. Your complete birthday gallery is ready whenever you want to see it again.', buttonLabel: 'Open your birthday gallery', textAnimation: 'letter_drift' },
    soundtrack: { title: 'Birthday Afternoon · Afrobeat Celebration', audioUrl: '/audio/ada-birthday.mp3' },
    theme: { accentColor: '#dc3f2f', secondaryColor: '#064735', glowColor: 'rgba(220, 63, 47, 0.34)' },
    photos: [
      frame('/veylo/lora/lora-1.jpeg', { chapterTitle: 'A SWEET BEGINNING', caption: 'Lora, that first proper smile beside the cake told us exactly how your birthday story should begin.', sceneLayout: 'cinema', transition: 'cut', typographyStyle: 'bold_banner', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'zoom_in', colorAccent: '#ef7950', secondaryColor: '#064735', visualAnalysis: { composition: 'Smiling three-quarter portrait with a white-and-green cake held at chest level', subject: 'Lora smiling beside her birthday cake', palette: ['burnt orange', 'emerald green', 'ivory', 'gold'], safeTextArea: 'upper left', mood: 'warm and joyful' } }),
      frame('/veylo/lora/lora-2.jpeg', { chapterTitle: 'ALL GROWN', caption: 'Then came this look—calm, sure of yourself, and completely at home in that green dress.', sceneLayout: 'poster', transition: 'scale', typographyStyle: 'editorial_quote', textAnimation: 'scale_pop', textBackground: 'vogue_bordered', captionPosition: 'bottom', zoomEffect: 'pan_down', colorAccent: '#d9a441', secondaryColor: '#064735', visualAnalysis: { composition: 'Three-quarter portrait with one hand resting at the waist', subject: 'Lora looking directly into the camera', palette: ['burnt orange', 'emerald green', 'gold'], safeTextArea: 'lower left', mood: 'confident and composed' } }),
      frame('/veylo/lora/lora-3.jpeg', { chapterTitle: 'MAKE A WISH', caption: 'You looked down at the cake for a second, and the whole session suddenly felt quiet and personal.', sceneLayout: 'split', transition: 'slide_left', typographyStyle: 'minimal_clean', textAnimation: 'smooth_slide', textBackground: 'solid_dark', captionPosition: 'right', zoomEffect: 'zoom_out', colorAccent: '#f0a58d', secondaryColor: '#064735', visualAnalysis: { composition: 'Three-quarter portrait with an ivory cake held at waist level', subject: 'Lora looking down at her birthday cake', palette: ['burnt orange', 'emerald green', 'ivory', 'gold'], safeTextArea: 'left edge', mood: 'soft and thoughtful' } }),
      frame('/veylo/lora/lora-4.jpeg', { chapterTitle: 'THIS SMILE', caption: 'This is the smile we would send to anyone who asked how your birthday went.', sceneLayout: 'cinema', transition: 'rise', typographyStyle: 'cinematic_drift', textAnimation: 'blur_reveal', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'pan_up', colorAccent: '#d93c32', secondaryColor: '#064735', visualAnalysis: { composition: 'Relaxed three-quarter portrait with a broad smile', subject: 'Lora smiling directly at the camera', palette: ['warm orange', 'emerald green', 'gold'], safeTextArea: 'upper right', mood: 'open and happy' } }),
      frame('/veylo/lora/lora-5.jpeg', { chapterTitle: 'YOUR MOMENT', caption: 'That side glance and the calm in this frame felt completely like you.', sceneLayout: 'collage', transition: 'cut', typographyStyle: 'typewriter', textAnimation: 'word_fade_up', textBackground: 'frosted_glass', captionPosition: 'bottom', zoomEffect: 'pan_right', colorAccent: '#c9362d', secondaryColor: '#0a4d39', visualAnalysis: { composition: 'Close side-facing portrait with one hand near the chin', subject: 'Lora sharing a quieter expression', palette: ['burnt orange', 'emerald green', 'gold'], safeTextArea: 'lower right', mood: 'quiet and self-assured' } }),
      frame('/veylo/lora/lora-6.jpeg', { chapterTitle: 'HAPPY BIRTHDAY, LORA', caption: 'And this was the photograph to end on: you, smiling properly, with another good year ahead of you.', sceneLayout: 'cinema', transition: 'fade', typographyStyle: 'editorial_quote', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'zoom_in', colorAccent: '#d9a441', secondaryColor: '#064735', visualAnalysis: { composition: 'Centred smiling portrait holding a small cream gift box', subject: 'Lora closing the session with a full smile', palette: ['burnt orange', 'emerald green', 'cream', 'gold'], safeTextArea: 'upper left', mood: 'celebratory close' } })
    ]
  },
  {
    id: 'ada', label: 'Ada · 30th Birthday', genre: 'Milestone Shoot', title: 'Ada Turns Thirty', clientName: 'Ada Eze', studioName: 'Apex Imagery Lekki', occasion: '30th birthday portraits · Lekki, Lagos',
    photographerBrief: 'Ada’s 30th birthday shoot. She chose an emerald suit and a vintage ivory telephone for a playful fashion set that still felt grown and confident.',
    storySummary: 'Ada, this session was your way of celebrating thirty—bold, playful, and full of personality. Here are a few moments from the day you stepped into a new decade.',
    opening: { eyebrow: 'Apex Imagery presents', headline: 'Ada, welcome to thirty.', copy: 'You chose the green suit and a set that felt just like you. Happy 30th birthday.', buttonLabel: 'See your birthday story', hint: 'Sound on. Tap either side when you want to move.' },
    finale: { eyebrow: 'Ada is thirty', headline: 'Happy 30th birthday, Ada.', copy: 'May this new decade bring you more laughter, bigger wins, and many more reasons to celebrate.', buttonLabel: 'Open your birthday gallery', textAnimation: 'letter_drift' },
    soundtrack: { title: 'Lekki Golden Hour · Afrobeat Celebration', audioUrl: '/audio/ada-birthday.mp3' },
    theme: { accentColor: '#ef3f35', secondaryColor: '#0b5b43', glowColor: 'rgba(239, 63, 53, 0.34)' },
    photos: [
      frame('/veylo/ada/ada-1.jpg', { chapterTitle: 'HELLO, THIRTY', caption: 'Ada, this was the moment your 30th birthday story began.', sceneLayout: 'cinema', transition: 'cut', typographyStyle: 'bold_banner', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'zoom_in', colorAccent: '#ef3f35', secondaryColor: '#0b5b43', visualAnalysis: { composition: 'Standing three-quarter portrait with the telephone held low', subject: 'Ada holding an ivory handset at her waist', palette: ['emerald green', 'aubergine', 'ivory', 'gold'], safeTextArea: 'lower left', mood: 'assured and playful' } }),
      frame('/veylo/ada/ada-2.jpg', { chapterTitle: 'YOUR PLAYFUL SIDE', caption: 'You brought your playful side to this one, and we enjoyed every second of it.', sceneLayout: 'poster', transition: 'scale', typographyStyle: 'editorial_quote', textAnimation: 'scale_pop', textBackground: 'vogue_bordered', captionPosition: 'bottom', zoomEffect: 'pan_down', colorAccent: '#d9a441', secondaryColor: '#0b5b43', visualAnalysis: { composition: 'Waist-up three-quarter portrait with one hand at the cuff', subject: 'Ada turning toward the light in her emerald suit', palette: ['emerald velvet', 'burgundy', 'gold'], safeTextArea: 'lower right', mood: 'knowing and composed' } }),
      frame('/veylo/ada/ada-3.jpg', { chapterTitle: 'THIRTY LOOKS GOOD', caption: 'You walked straight through the set and made turning thirty look very good.', sceneLayout: 'split', transition: 'slide_left', typographyStyle: 'minimal_clean', textAnimation: 'smooth_slide', textBackground: 'solid_dark', captionPosition: 'right', zoomEffect: 'zoom_out', colorAccent: '#0f6b4e', secondaryColor: '#ef3f35', visualAnalysis: { composition: 'Full-length walking portrait with an ivory receiver held low', subject: 'Ada crossing the wine-coloured set', palette: ['deep green', 'ivory', 'wine'], safeTextArea: 'left edge', mood: 'cool and unhurried' } }),
      frame('/veylo/ada/ada-4.jpg', { chapterTitle: 'LOOK AT YOU', caption: 'Ada, this is the confidence we saw in you throughout your birthday session.', sceneLayout: 'cinema', transition: 'rise', typographyStyle: 'cinematic_drift', textAnimation: 'blur_reveal', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'pan_up', colorAccent: '#ef3f35', secondaryColor: '#0b5b43', visualAnalysis: { composition: 'Close side portrait beside a translucent plum panel', subject: 'Ada looking back toward the camera', palette: ['emerald green', 'plum', 'gold'], safeTextArea: 'upper left', mood: 'commanding' } }),
      frame('/veylo/ada/ada-5.jpg', { chapterTitle: 'CHEERS TO YOU', caption: 'Here’s to you, Ada, and all the good things waiting for you at thirty.', sceneLayout: 'collage', transition: 'cut', typographyStyle: 'typewriter', textAnimation: 'word_fade_up', textBackground: 'frosted_glass', captionPosition: 'bottom', zoomEffect: 'pan_right', colorAccent: '#d9a441', secondaryColor: '#7f1d1d', visualAnalysis: { composition: 'Standing portrait beside a curved burgundy plinth', subject: 'Ada holding an ivory receiver low against the plinth', palette: ['emerald velvet', 'burgundy', 'ivory', 'gold'], safeTextArea: 'lower left', mood: 'bold closing look' } })
    ]
  },
  {
    id: 'wedding', label: 'Folake & Tunde · Wedding', genre: 'Traditional Wedding', title: 'Folake & Tunde’s Day', clientName: 'Folake & Tunde', studioName: 'Mayflower Visuals', occasion: 'Traditional wedding portraits · Ikeja, Lagos',
    photographerBrief: 'Folake and Tunde’s traditional wedding portraits, made just before they joined their guests. Tell a warm story about the couple, their love, and the beginning of their marriage.',
    storySummary: 'Folake and Tunde, before you joined your family and friends, you had a few quiet moments together. This is how your wedding story began.',
    opening: { eyebrow: 'Mayflower Visuals presents', headline: 'Folake and Tunde, this is your day.', copy: 'Before the music and celebration, we had a few quiet minutes to photograph the two of you together.', buttonLabel: 'See your wedding story' },
    finale: { eyebrow: 'Folake & Tunde are married', headline: 'Congratulations, Folake and Tunde.', copy: 'May the love and happiness you shared on this day stay with you through every year ahead.', buttonLabel: 'Open your wedding gallery', textAnimation: 'word_fade_up' },
    soundtrack: { title: 'The Two of Us · Soft Wedding Highlife', audioUrl: '/audio/soundtrack-1.mp3' },
    theme: { accentColor: '#c89445', secondaryColor: '#5f341d', glowColor: 'rgba(200, 148, 69, 0.32)' },
    photos: [
      frame('/veylo/wedding/wedding-1.jpg', { chapterTitle: 'YOUR WEDDING DAY', caption: 'Folake, the way Tunde looked at you here said everything.', sceneLayout: 'cinema', transition: 'fade', typographyStyle: 'editorial_quote', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'zoom_in', colorAccent: '#c89445', visualAnalysis: { composition: 'Couple seated and standing by bright glass wall', palette: ['bronze', 'gold', 'garden green'], safeTextArea: 'upper left', mood: 'tender' } }),
      frame('/veylo/wedding/wedding-2.jpg', { chapterTitle: 'CLOSE TO YOU', caption: 'You moved closer, and Tunde could not hide that smile.', sceneLayout: 'split', transition: 'slide_left', typographyStyle: 'minimal_clean', textAnimation: 'smooth_slide', textBackground: 'solid_dark', captionPosition: 'right', zoomEffect: 'pan_down', colorAccent: '#79522d', visualAnalysis: { composition: 'Standing couple, bride foreground', palette: ['copper', 'honey', 'green'], safeTextArea: 'right', mood: 'easy affection' } }),
      frame('/veylo/wedding/wedding-3.jpg', { chapterTitle: 'SIDE BY SIDE', caption: 'Together looked easy on both of you, just as it should on your wedding day.', sceneLayout: 'poster', transition: 'scale', typographyStyle: 'cinematic_drift', textAnimation: 'blur_reveal', textBackground: 'vogue_bordered', captionPosition: 'bottom', zoomEffect: 'zoom_out', colorAccent: '#c89445', visualAnalysis: { composition: 'Groom seated, bride standing beside him', palette: ['gold', 'bronze', 'leaf green'], safeTextArea: 'upper right', mood: 'familiar and warm' } }),
      frame('/veylo/wedding/wedding-4.jpg', { chapterTitle: 'JUST THE TWO OF YOU', caption: 'For a moment, the celebration could wait. This time belonged to both of you.', sceneLayout: 'collage', transition: 'rise', typographyStyle: 'editorial_quote', textAnimation: 'letter_drift', textBackground: 'frosted_glass', captionPosition: 'bottom', zoomEffect: 'pan_right', colorAccent: '#d8aa61', visualAnalysis: { composition: 'Full-length couple standing close', palette: ['mustard', 'bronze', 'cream'], safeTextArea: 'lower left', mood: 'quietly joyful' } }),
      frame('/veylo/wedding/wedding-5.jpg', { chapterTitle: 'LET THE CELEBRATION BEGIN', caption: 'One kiss, then off you went to celebrate with everyone who came for you.', sceneLayout: 'cinema', transition: 'fade', typographyStyle: 'typewriter', textAnimation: 'word_fade_up', textBackground: 'transparent_shadow', captionPosition: 'bottom', zoomEffect: 'zoom_in', colorAccent: '#c89445', visualAnalysis: { composition: 'Standing embrace and cheek kiss', palette: ['warm gold', 'bronze', 'soft green'], safeTextArea: 'lower right', mood: 'affectionate close' } })
    ]
  }
];

