// The public Event Coverage demo is deliberately a small, believable event
// record rather than a handful of unrelated format placeholders. Each frame
// carries the kind of moment a guest or organiser may want to find again.
export const EVENT_COVERAGE_DEMO_PHOTOS = [
  { name: '/veylo/demo/event/event-01-arrivals.webp', alt: 'Attendees arriving and checking in at a Lagos conference', caption: 'The day starts at the registration desk. Guests collect their badges, greet one another and pause for a conversation in the busy entrance hall.', eventType: 'people' },
  { name: '/veylo/demo/event/event-02-keynote.webp', alt: 'A speaker addressing a seated conference audience', caption: 'The opening address is underway. From the lectern, the speaker looks out across the seated guests as the room turns its attention to the stage.', eventType: 'programme' },
  { name: '/veylo/demo/event/event-03-networking.webp', alt: 'Attendees talking over refreshments during a networking break', caption: 'A break for coffee and conversation. Small groups gather in the bright foyer, refreshments in hand, with plenty to talk about between sessions.', eventType: 'networking' },
  { name: '/veylo/demo/event/event-04-stage.webp', alt: 'Singers and musicians performing while guests record on their phones', caption: 'The band has the room watching. Singers in colourful traditional attire take the front of the stage while guests raise their phones to record.', eventType: 'programme' },
  { name: '/veylo/demo/event/event-05-details.webp', alt: 'Name badges and event materials arranged on a registration table', caption: 'Everything laid out for the guests. At the registration table, hands sort black lanyards beside neat stacks of notebooks and programme folders.', eventType: 'details' },
  { name: '/veylo/demo/event/event-06-arrivals-greeting.webp', alt: 'Two attendees greeting each other at a conference registration desk', caption: 'A handshake at the welcome desk. Two guests stop to greet each other with a smile, just beside the registration table.', eventType: 'people' },
  { name: '/veylo/demo/event/event-07-keynote-wide.webp', alt: 'A keynote speaker addressing a full Nigerian conference hall', caption: 'A view from the back of the hall. Rows of seated guests face the lectern, with the speaker framed by the warm lights along the walls.', eventType: 'programme' },
  { name: '/veylo/demo/event/event-08-keynote-speaker.webp', alt: 'A Nigerian speaker speaking into a microphone from her seat on stage', caption: 'A closer look at the speaker. Seated on stage, she holds the microphone in one hand and gestures with the other as she makes her point.', eventType: 'programme' },
  { name: '/veylo/demo/event/event-09-audience-applause.webp', alt: 'Conference attendees smiling and applauding', caption: 'Applause across the front rows. Guests smile and clap together, while others stand just behind them with their eyes still on the stage.', eventType: 'people' },
  { name: '/veylo/demo/event/event-10-networking-conversation.webp', alt: 'Three professionals talking during a conference networking break', caption: 'The conversation carries on over coffee. Three guests share a laugh around a table in the foyer, cups still in hand.', eventType: 'networking' },
  { name: '/veylo/demo/event/event-11-audience-notes.webp', alt: 'An attendee taking notes during a conference session', caption: 'A page of notes from the session. With a notebook resting on his lap, a guest writes as the programme continues on stage behind him.', eventType: 'people' },
  { name: '/veylo/demo/event/event-12-panel-discussion.webp', alt: 'A panel of Nigerian speakers discussing a topic on stage', caption: 'Four voices on the panel. One panellist speaks into the microphone while the others listen from their chairs, a notebook open beside him.', eventType: 'programme' },
  { name: '/veylo/demo/event/event-13-partner-table.webp', alt: 'A partner display table with an attendee speaking to a vendor', caption: 'A stop at the partner stand. A guest with a tablet chats across a display of boxed products and glass jars, with white flowers at the edge.', eventType: 'networking' },
  { name: '/veylo/demo/event/event-14-venue-arrival.webp', alt: 'Attendees walking into a modern Lagos conference venue', caption: 'On the way into the venue. Guests walk up the broad entrance steps towards the glass-fronted building, passing the palms outside.', eventType: 'details' },
  { name: '/veylo/demo/event/event-15-networking-group.webp', alt: 'A group of Nigerian guests laughing together beside the refreshments', caption: 'One more laugh by the refreshments. Five guests gather with coffee cups and a plate of pastries, enjoying a conversation away from the hall.', eventType: 'people' },
  { name: '/veylo/demo/event/event-16-stage-performance.webp', alt: 'A cultural performance on stage while conference guests watch', caption: 'The dancer takes the front of the stage. Behind her, the talking drummer and musicians play while guests watch and hold up their phones.', eventType: 'programme' }
];
