export const SHOOT_TYPES = [
  'Birthday',
  'Wedding',
  'Traditional Wedding',
  'Engagement',
  'Pre-Wedding',
  'Graduation',
  'Maternity',
  'Newborn',
  'Anniversary',
  'Portrait',
  'Fashion',
  'Lookbook',
  'Personal Branding',
  'Corporate',
  'Commercial',
  'Event',
  'Bridal Shower',
  'Owambe',
  'Studio Portrait',
  'Memorial',
  'Other'
];
