import React from 'react';
import { Camera, Clapperboard, Send } from 'lucide-react';
import { Action, EndNote, Eyebrow, Page, Photo, Reveal, TextLink } from '../components/PublicDesign.jsx';

export default function AboutUs() {
  return <Page><header className="v-wrap v-editorial-hero"><Reveal><Eyebrow>About Veylo / Made in Nigeria</Eyebrow><h1 className="v-title">Care does not end<br />at the <em>last edit.</em></h1><p className="v-lead">A finished shoot deserves more than a cold folder link. Veylo helps photographers decide how the work should arrive, then keeps the complete gallery and downloads close behind.</p><div className="v-actions"><Action to="/#formats">Meet the six formats</Action></div></Reveal><Reveal className="v-editorial-image"><Photo name="photographer" alt="A photographer working in her studio" eager /></Reveal></header>
    <section className="v-section"><div className="v-wrap"><Reveal><Eyebrow number="01">Why we are here</Eyebrow><h2 className="v-about-statement mt-8">The client has waited through the shoot, the editing, and the final export.<br /><span>The first viewing should feel worth the wait.</span></h2></Reveal><div className="v-values">{[[Camera, 'The photograph comes first.', 'The lighting, colour, expression, and retouching belong to the photographer. Veylo designs around that finished work.'], [Clapperboard, 'Every shoot asks for something different.', 'A wedding may need chapters. A portrait client may want a reveal. A campaign may belong on an editorial page.'], [Send, 'Made for the way you send.', 'A client asks on WhatsApp. A family shares a link in a group chat. Veylo fits into those real conversations.']].map(([Icon, title, copy], i) => <Reveal key={title} className="v-value" delay={i * .06}><Icon size={22} className="text-[#ff9b8e]" /><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></div></section>
    <section className="v-section v-workflow"><div className="v-wrap v-spread"><Reveal className="v-niche-photos"><figure><Photo name="portrait-soft" alt="A softly lit finished portrait" /><figcaption>For the quiet frames.</figcaption></figure><figure><Photo name="portrait-reaching" alt="A finished editorial portrait" /><figcaption>For the bold ideas.</figcaption></figure></Reveal><Reveal><Eyebrow number="02">Built here, for the work</Eyebrow><h2 className="v-heading">Nigeria first.<br /><em>Photographers first.</em></h2><p className="v-copy">Veylo is a product of Tech-City Technology in Nigeria. We are building for photographers and media studios who deliver through mobile conversations and want the handover to reflect the standard of their work.</p><p className="v-copy mt-5">Have a delivery problem we should understand? Tell us about it.</p><div className="mt-6"><TextLink to="/contact">Talk to the team</TextLink></div></Reveal></div></section><EndNote />
  </Page>;
}

