import React from 'react';
import PolicyPage from '../components/PolicyPage.jsx';

const sections = [
  { id: 'who-we-are', title: 'Who we are', paragraphs: ['Veylo is a photo presentation and delivery platform operated by Tech-City Technology in Nigeria. It helps photographers turn finished shoots into designed client experiences followed by downloadable galleries.'] },
  { id: 'information', title: 'Information used by Veylo', paragraphs: ['The service uses information you provide to create an account, prepare a delivery, and build a portfolio when you choose to publish one.'], items: ['Account details such as your name, email address, password hash, and plan.', 'Shoot content such as photographs, client names, shoot context, titles, captions, music, and narration choices.', 'Portfolio content such as studio information, location, social links, categories, and selected work.', 'Delivery activity such as view and download counts.', 'Payment references, subscription dates, refund records, and paid-service activity, including activity for later-deleted work. Veylo charges the same NGN Pro price regardless of location; a country check is not used to set your price.', 'Support correspondence you choose to send us.'] },
  { id: 'how-it-is-used', title: 'How information is used', paragraphs: ['Account information supports sign-in and account management. Photographs and shoot details are used to prepare, display, host, and deliver the experiences you request.', 'When an AI-assisted feature is used, the information needed for that feature may be processed by an external AI service. Review shoot context before submitting it, avoid unnecessary confidential information, and check the result before publishing.'] },
  { id: 'providers', title: 'Hosting and service providers', paragraphs: ['Veylo uses MongoDB Atlas for account and project records, Cloudflare R2 for photographs and audio, Paystack for subscriptions, and Resend for email. Groq AI handles creative direction, delivery preparation, photo analysis, captions, Veylo Help, and brief assistance. Alibaba Model Studio can handle those AI requests when Groq is unavailable, and generates optional supporting images in Content Studio. Deepgram provides optional narration, Google provides Google sign-in, and Cloudflare Turnstile supports security checks. Each provider receives only the information needed for its part of the service.'] },
  { id: 'delivery-access', title: 'Who can access shared photographs', paragraphs: ['A person with a published delivery link may be able to open it and download the photographs. A recipient can forward the link or downloaded files to another person.', 'Veylo Pro client preselection and editor handoff links share selected Image Library photographs with the person who has the link. You can protect a client link with an optional PIN; editor links require a password. Share links and access details only with the intended person.', 'Before publishing or sharing, make sure you have permission to share the photographs and any client information included.'] },
  { id: 'portfolio-access', title: 'Public portfolios', paragraphs: ['A published Veylo Portfolio is public. Only add photographs, studio information, contact details, and links you intend visitors to see.'] },
  { id: 'portfolio-enquiries', title: 'Portfolio enquiries', paragraphs: ['When you send an enquiry through a portfolio, Veylo saves your name, chosen reply address or WhatsApp number, shoot details and message in that photographer’s private inbox. The photographer can use those details to reply. Sending an enquiry does not confirm a booking.', 'Email notifications tell the photographer that an enquiry has arrived without including your message or contact details. Enquiry information stays separate from service analytics. It is removed when the photographer’s account is deleted or their retained portfolio data is deleted after Pro ends. Contact Veylo if you need help with a privacy request about an enquiry.'] },
  { id: 'storage', title: 'Storage and deletion', paragraphs: ['Signed-in photographers can manage their projects through their account. Copies already downloaded by recipients remain outside Veylo’s control.', 'When Pro ends, personal Image Library files and portfolio data are kept privately for 30 days before deletion. Published client deliveries use separate hosting and do not count toward the 100 GB Image Library allowance.', 'You can permanently delete your Veylo account from Account Settings. This removes the account, studio profile, portfolio, delivery records, sessions, verification records, and Veylo-hosted files connected to that account. Veylo keeps a restricted financial ledger for six years after account deletion for accounting, refund reviews, and payment disputes. It retains payment references, amounts, subscription dates, review reasons, and minimal service-usage evidence, without your studio profile, stored files, card credentials, or provider management tokens. Unfinished payment events may be kept encrypted until recovery completes, then their raw contents are removed when the account has been deleted. Paystack may retain its own transaction records. Keep your own backups of finished photographs.'] },
  { id: 'browser-storage', title: 'Cookies and browser storage', paragraphs: ['Veylo uses necessary authentication and CSRF cookies to keep signed-in accounts secure. It also uses scoped delivery-access cookies, security-provider storage when Google sign-in or Cloudflare Turnstile is used, and browser storage for the notice preference.', 'Veylo also records first-party service analytics so we can measure visits, page paths, device type, delivery opens, downloads, failures, and other product outcomes. Session and visitor identifiers are hashed before they reach the database. We do not record passwords, PINs, contact details, private briefs, captions, photograph pixels, audio, message contents, or keystrokes, and we do not use advertising cookies. Analytics events are removed automatically after the configured retention window (365 days by default). When enabled, PostHog receives a selected set of service events through our server, using pseudonymous account or session identifiers. Those events describe product outcomes and sanitised browser code locations; they exclude names, contact details, private links, photograph pixels and message contents. This integration does not record your screen or keystrokes. Copies held by PostHog have their own project retention settings. Contact Veylo for access or deletion requests covering those copies. Cookie details remain available from the footer.'] },
  { id: 'privacy-contact', title: 'Questions and requests', paragraphs: ['For a privacy question, account correction, or deletion request, contact the team. Include enough information to identify the account or delivery, but never send your password.'], contact: true }
];

export default function PrivacyPolicy() {
  return <PolicyPage title="Privacy, explained." description="What the service uses, how published links work, and where to send a privacy request." note="Only publish photographs and client details you have permission to share through a client delivery or public portfolio." sections={sections} />;
}
