import React from 'react';
import PolicyPage from '../components/PolicyPage.jsx';
const sections = [
  { id: 'request', title: 'How to ask for a refund', paragraphs: ['Send a message through Support while signed in, choose Veylo Pro and the payment you want reviewed, or email payment@veylo.com.ng from your account email. For email requests, include your payment reference, payment date, amount, and what went wrong. You can always ask us to review a payment; sending a request does not guarantee approval.'], contact: 'payment@veylo.com.ng' },
  { id: 'first-payment', title: 'Changed your mind after your first payment?', paragraphs: ['You can request a change-of-mind refund within seven days of your first Pro payment, provided you have not published a client delivery during that paid period or used paid personal storage or Portfolio features.', 'We review service activity during the paid period, including activity for deliveries or files later deleted. If you have already used those services, the payment is not eligible for a routine change-of-mind refund.'] },
  { id: 'used-service', title: 'Used months and renewals', paragraphs: ['We do not routinely refund used subscription periods, renewal payments, unused days, or unused storage. Cancel before your next renewal to stop future charges. Cancellation keeps access through the time you already paid for.'] },
  { id: 'payment-errors', title: 'When we review a refund even after use', items: ['A duplicate charge for the same subscription period.', 'A charge after Veylo or Paystack confirmed that renewal was canceled.', 'A confirmed payment where the paid access was not provided.', 'A material service failure that prevented the paid service from being provided.'], paragraphs: ['These requests are reviewed on their facts regardless of service usage. Keep the payment receipt and any cancellation confirmation. This policy does not limit remedies you are entitled to under applicable consumer law.'] },
  { id: 'processing', title: 'If a refund is approved', paragraphs: ['Refunds go through Paystack in the currency of the original charge, Nigerian naira. Your bank determines when the funds appear and any currency conversion. Exchange rates or bank fees can affect the amount shown in your own currency.', 'We will tell you if the refund is processing, completed, failed, or needs more information. A requested refund is not a completed refund. Email payment@veylo.com.ng with your reference if you need an update.'] },
  { id: 'access', title: 'Refunds and subscription cancellation', paragraphs: ['A full refund removes access funded by that payment. Refunding an older payment does not remove access funded by a newer valid payment. Partial refunds do not automatically end Pro access.', 'Refund approval and stopping renewal are separate actions. Cancel from Billing if you want future payments stopped, or ask us to confirm that cancellation as part of the review.'] }
];
export default function RefundPolicy() {
  return <PolicyPage title="Refunds and payment help." description="When a refund can apply, how we review it, and where to get help with a charge." sections={sections} />;
}
