import React from 'react';
import PolicyPage from '../components/PolicyPage.jsx';

const sections = [
  { id: 'video-delivery', title: 'Finished video delivery on Pro', paragraphs: ['Pro video delivery hosts finished client films in a separate video delivery. Original files share your Pro storage allowance; stored duration and delivered playback minutes have their own limits shown in the product and account pages. You are responsible for permission to host and share all footage, voices and soundtrack material.', 'Optional AI suggestions use sampled footage and, only when requested, spoken content. Review factual details and private information before using or publishing suggestions. Playback copies are prepared for browser viewing; permitted original downloads retain the file you uploaded.', 'Paid-through cancellation keeps Pro access until it expires. Client video links then pause. Original files are kept privately for a 30-day recovery period with owner downloads available; renew before cleanup to restore hosting. After the period ends, originals, playback copies and analysis are removed. Keep independent backups.'] },
  { id: 'agreement', title: 'Using Veylo', paragraphs: ['Veylo is operated by Tech-City Technology in Nigeria. By registering, creating a delivery, or delivering photographs through Veylo, you agree to these terms. If you use Veylo for a studio or company, you confirm that you have authority to act on its behalf.'] },
  { id: 'service', title: 'What the service is for', paragraphs: ['Veylo is for presenting and delivering finished photographic shoots. Clients can swipe through a Photo Swap, browse the complete gallery on GridBoard, or view a Showcase presentation in Photo Story, Editorial Page, Photo Reveal, Canvas, Chapters, Album, Event Coverage, or Campaign Delivery.', 'Veylo Pro also includes private Image Library links for client photo preselection and editor handoff. A client can choose photographs for editing, and an invited editor can download camera originals and return edited files. Preselection links can use a PIN; editor links require a password. All links use Image Library storage and close when revoked, expired, or Pro access ends.', 'Keep your original files and master backups. A JPEG preview made from a camera RAW file is for review and does not replace the RAW original.'] },
  { id: 'ownership', title: 'Your work and your permissions', paragraphs: ['You keep your ownership rights in the content you upload. You grant Veylo a limited, non-exclusive permission to store, process, display, and deliver that content as needed to provide the service.', 'You are responsible for having the necessary rights and client permissions for the photographs, music, narration, and text you upload or share. Choosing a soundtrack does not transfer ownership of that music to you.'] },
  { id: 'account', title: 'Your account', paragraphs: ['Keep your sign-in details private and provide accurate account information. You are responsible for activity carried out through your account. Contact us if you believe someone else has accessed it.'] },
  { id: 'plans', title: 'Plans and pricing', paragraphs: ['Veylo Free is ₦0 per month and includes three final photo deliveries each month, up to 100 photographs in each delivery, Photo Swap, GridBoard and the eight Showcase formats, and Veylo branding on deliveries.', 'Veylo Pro is ₦40,000 per month for every customer, charged in NGN. It includes unlimited final photo deliveries under fair use, up to 500 photographs in each delivery, Photo Swap, GridBoard and the eight Showcase formats, Veylo Portfolio, custom studio branding, 100 GB in the personal Image Library, private client preselection links, and password-protected editor handoff links that use that storage. Photo delivery hosting stays separate from the Image Library allowance. Original videos share that allowance, and you can remove Veylo branding. Your bank or card provider may convert a naira charge into another currency and add a fee.', 'We will notify existing subscribers before a change to their renewal amount takes effect.'] },
  { id: 'billing', title: 'Monthly billing, cancellation, and failed payments', paragraphs: ['Veylo Pro renews monthly through Paystack. You can cancel from Billing at any time. Your Pro access continues until the end of the month you already paid for, and there is no annual commitment.', 'If a renewal fails, Veylo keeps Pro access open for three days from the failed invoice due date so you can update the payment method. Paystack does not automatically retry a failed subscription charge, so a new checkout may be required after the grace period.', 'When Pro ends, your personal library and portfolio remain private for 30 days. During that period you can download or remove stored photographs. Renewing Pro restores editing and publishing. After 30 days, retained library files and portfolio data are deleted.', 'Refund requests go to payment@veylo.com.ng. The refund policy at /refund-policy explains the seven-day first-payment window for unused service and the separate review of payment errors or material service failures. Refunding an older period does not remove access paid for by a newer valid payment. Cancellation and refunds are separate actions.'] },
  { id: 'delivery', title: 'Publishing and sharing', paragraphs: ['You decide who receives a delivery link. A recipient may forward a link or downloaded file, so choose the delivery audience carefully.', 'Review all generated titles, captions, organisation, and presentation decisions before publishing. You are responsible for the accuracy and suitability of the final delivery.'] },
  { id: 'conduct', title: 'Acceptable use', paragraphs: ['Use Veylo for your own finished client shoots and follow the fair use policy.'], items: ['Do not upload unlawful, abusive, or non-consensual imagery.', 'Do not share content that infringes another person’s rights.', 'Do not distribute malicious files, disrupt the service, or access another photographer’s account or content without permission.', 'Do not resell account access or use unauthorised automation to create deliveries in bulk.'] },
  { id: 'backups', title: 'Keep your own backups', paragraphs: ['Keep independent copies of your camera originals and finished exports. Do not rely on a delivery link, a shared preselection or editor link, or Veylo storage as your only archive.'] },
  { id: 'contact', title: 'Governing law and contact', paragraphs: ['These terms are governed by the laws of the Federal Republic of Nigeria. Contact Tech-City Technology with questions about these terms, your account, or the service.'], contact: true }
];

export default function TermsOfService() {
  return <PolicyPage title="Terms of use." description="The terms for creating an account, presenting your work, and delivering client photographs through Veylo." sections={sections} />;
}
