import React from 'react';
import PolicyPage from '../components/PolicyPage.jsx';

const sections = [
  { id: 'agreement', title: 'Using Veylo', paragraphs: ['Veylo is operated by Tech-City Technology in Nigeria. By registering, creating a delivery, or delivering photographs through Veylo, you agree to these terms. If you use Veylo for a studio or company, you confirm that you have authority to act on its behalf.'] },
  { id: 'service', title: 'What the service is for', paragraphs: ['Veylo is for presenting and delivering finished photographic shoots. Supported experiences can include Photo Story, Editorial Page, Photo Reveal, Canvas, Chapters, and Album, followed by a gallery of the photographer’s final files.', 'Upload completed exports, provide accurate context, review the presentation before publishing, and keep your original files and master backups.'] },
  { id: 'ownership', title: 'Your work and your permissions', paragraphs: ['You keep your ownership rights in the content you upload. You grant Veylo a limited, non-exclusive permission to store, process, display, and deliver that content as needed to provide the service.', 'You are responsible for having the necessary rights and client permissions for the photographs, music, narration, and text you upload or share. Choosing a soundtrack does not transfer ownership of that music to you.'] },
  { id: 'account', title: 'Your account', paragraphs: ['Keep your sign-in details private and provide accurate account information. You are responsible for activity carried out through your account. Contact us if you believe someone else has accessed it.'] },
  { id: 'plans', title: 'Plans and pricing', paragraphs: ['Veylo Free is ₦0 per month and includes three final photo deliveries each month, access to all delivery formats, and Veylo branding on deliveries.', 'Veylo Pro is ₦25,000 per month and includes unlimited final photo deliveries under fair use, all delivery formats, Veylo Portfolio, custom studio branding, 50 GB of personal image storage, delivery hosting outside that allowance, and the option to remove Veylo branding.', 'Any change to pricing or plan limits will be shown before it applies to a new billing period.'] },
  { id: 'delivery', title: 'Publishing and sharing', paragraphs: ['You decide who receives a delivery link. A recipient may forward a link or downloaded file, so choose the delivery audience carefully.', 'Review all generated titles, captions, organisation, and presentation decisions before publishing. You are responsible for the accuracy and suitability of the final delivery.'] },
  { id: 'conduct', title: 'Acceptable use', paragraphs: ['Use Veylo for your own finished client shoots and follow the fair use policy.'], items: ['Do not upload unlawful, abusive, or non-consensual imagery.', 'Do not share content that infringes another person’s rights.', 'Do not distribute malicious files, disrupt the service, or access another photographer’s account or content without permission.', 'Do not resell account access or use unauthorised automation to create deliveries in bulk.'] },
  { id: 'backups', title: 'Keep your own backups', paragraphs: ['Veylo is a client presentation and delivery service. Keep independent copies of your original photographs and finished exports. Do not rely on a delivery link or Veylo storage as your only archive.'] },
  { id: 'contact', title: 'Governing law and contact', paragraphs: ['These terms are governed by the laws of the Federal Republic of Nigeria. Contact Tech-City Technology with questions about these terms, your account, or the service.'], contact: true }
];

export default function TermsOfService() {
  return <PolicyPage title="Terms of use." description="The terms for creating an account, presenting your work, and delivering client photographs through Veylo." sections={sections} />;
}
