import express from 'express';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { checkPortfolioHandle, directMyPortfolio, getMyPortfolio, getPortfolioJob, getPortfolioSources, getPublicPortfolio, publishMyPortfolio, recordPortfolioEngagement, unpublishMyPortfolio, updateMyPortfolio } from '../controllers/portfolio.controller.js';
import { aiGenerationLimit } from '../middleware/rateLimit.middleware.js';
import { publicAccessLimit } from '../middleware/rateLimit.middleware.js';
import { getPortfolioMedia, getPortfolioSourceMedia, getPortfolioShareMeta, getPortfolioActivity, cancelPortfolioJob, reviewPortfolioJob } from '../controllers/portfolioV2.controller.js';

const router = express.Router();
router.get('/public/:handle', publicAccessLimit, getPublicPortfolio);
router.get('/public/:handle/projects/:projectId', publicAccessLimit, getPublicPortfolio);
router.get('/public/:handle/share-meta', publicAccessLimit, getPortfolioShareMeta);
router.get('/public/:handle/projects/:projectId/share-meta', publicAccessLimit, getPortfolioShareMeta);
router.get('/public/:handle/media/:itemId', publicAccessLimit, getPortfolioMedia);
router.post('/public/:handle/engagement', publicAccessLimit, recordPortfolioEngagement);
router.use(authMiddleware);
router.get('/mine', getMyPortfolio);
router.get('/mine/media/:itemId', getPortfolioMedia);
router.get('/mine/source-media', getPortfolioSourceMedia);
router.get('/mine/activity', getPortfolioActivity);
router.get('/handles/:handle/availability', checkPortfolioHandle);
router.get('/sources', getPortfolioSources);
router.put('/mine', updateMyPortfolio);
router.post('/mine/publish', publishMyPortfolio);
router.post('/mine/unpublish', unpublishMyPortfolio);
router.post('/mine/direct', aiGenerationLimit, directMyPortfolio);
router.get('/mine/jobs/:jobId', getPortfolioJob);
router.post('/mine/jobs/:jobId/cancel', cancelPortfolioJob);
router.post('/mine/jobs/:jobId/review', reviewPortfolioJob);
export default router;
