import express from 'express';
import multer from 'multer';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { mediaSignatureLimit, privateLinkMediaLimit, privateLinkUnlockLimit, privateLinkUploadLimit, publicAccessLimit, aiGenerationLimit } from '../middleware/rateLimit.middleware.js';
import * as video from '../controllers/video.controller.js';

const router = express.Router();
const poster = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10_000_000, files: 1, fields: 2 }, fileFilter: (req, file, done) => done(null, ['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)) });
router.get('/config', publicAccessLimit, video.getVideoConfig);
router.get('/public/:publicId', publicAccessLimit, video.getPublicVideo);
router.post('/public/:publicId/unlock', privateLinkUnlockLimit, video.unlockPublicVideo);
router.post('/public/:publicId/assets/:assetId/playback', publicAccessLimit, video.startPublicVideo);
router.post('/public/:publicId/playback/end', publicAccessLimit, video.endVideoPlayback);
router.get('/public/:publicId/assets/:assetId/poster', privateLinkMediaLimit, video.getPublicVideoPoster);
router.get('/public/:publicId/assets/:assetId/download', privateLinkMediaLimit, video.downloadPublicVideo);
router.use(authMiddleware);
router.get('/presentations/:jobId', video.getVideoPresentationJob);
router.get('/assets', video.listVideoAssets);
router.get('/assets/:assetId/poster', video.getOwnerVideoPoster);
router.get('/assets/:assetId/download', privateLinkMediaLimit, video.downloadOwnerVideo);
router.post('/assets/:assetId/poster', privateLinkUploadLimit, poster.single('poster'), video.setVideoPoster);
router.post('/assets/:assetId/retry', video.retryVideoAsset);
router.post('/assets/:assetId/analyze', aiGenerationLimit, video.requestVideoAnalysis);
router.delete('/assets/:assetId', video.deleteVideoAsset);
router.get('/uploads/:uploadId', video.getVideoUpload);
router.post('/uploads/:uploadId/part', mediaSignatureLimit, video.signVideoPart);
router.post('/uploads/:uploadId/pause', video.pauseVideoUpload);
router.post('/uploads/:uploadId/complete', video.completeVideoUpload);
router.delete('/uploads/:uploadId', video.abortVideoUpload);
router.post('/deliveries', video.createVideoDelivery);
router.get('/deliveries/:id', video.getVideoDelivery);
router.patch('/deliveries/:id', video.saveVideoDraft);
router.patch('/deliveries/:id/access', video.saveVideoAccess);
router.post('/deliveries/:id/publish', video.publishVideoDelivery);
router.post('/deliveries/:id/suggest', aiGenerationLimit, video.requestVideoPresentation);
router.post('/deliveries/:id/close', video.closeVideoDelivery);
router.get('/deliveries/:id/preview', video.getVideoPreview);
router.post('/deliveries/:id/playback/end', video.endPreviewPlayback);
router.post('/deliveries/:id/assets/:assetId/playback', publicAccessLimit, video.startPreviewVideo);
router.post('/deliveries/:id/uploads', privateLinkUploadLimit, video.initializeVideoUpload);
router.use((error, req, res, next) => {
  if (error instanceof multer.MulterError) return res.status(400).json({ success: false, message: error.code === 'LIMIT_FILE_SIZE' ? 'Choose a cover image smaller than 10 MB.' : 'Choose one cover image and try again.' });
  next(error);
});
export default router;
