import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Activity, ArrowRight, ArrowUpRight, Check, CircleHelp, Clock3, Cpu, Database, HardDrive, Mail, RefreshCw, Server, TriangleAlert, Users } from 'lucide-react';
import api from '../services/api.js';
import { useVeyloReducedMotion } from '../../../client/src/utils/motionPolicy.js';

const numeric = value => Number.isFinite(value) ? new Intl.NumberFormat('en-NG', { maximumFractionDigits: 1 }).format(value) : '—';
const bytes = value => Number.isFinite(value) ? `${numeric(value / 1024 ** 2)} MB` : '—';
export const checkedTime = value => value ? new Date(value).toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : 'No check received';
const statusLabel = status => ({ healthy: 'Passing', configured: 'Configured', unconfigured: 'Not configured', disabled: 'Disabled', unknown: 'No observation', stale: 'Stale', unavailable: 'Unavailable', degraded: 'Needs attention', idle: 'Reporting', busy: 'Working', error: 'Error' }[status] || 'Unknown');
function State({ status = 'unknown' }) { return <span className={`aw-state aw-state-${status}`}><i />{statusLabel(status)}</span>; }
export function WorkspaceHeading({ eyebrow, title, description, loading, onRefresh, updatedAt }) {
  const reduced = useVeyloReducedMotion();
  return <motion.div className="aw-heading" initial={{ opacity: 0, y: reduced ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35 }}><div><p className="aw-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="aw-description">{description}</p></div><div className="aw-refresh"><button type="button" disabled={loading} onClick={onRefresh}><RefreshCw size={15} className={loading ? 'animate-spin' : ''} />{loading ? 'Refreshing' : 'Refresh'}</button><span>{updatedAt ? `Updated ${checkedTime(updatedAt)}` : 'Waiting for data'}</span></div></motion.div>;
}
function Stat({ icon: Icon, label, value, note }) { return <article className="aw-stat"><div><span>{label}</span><Icon size={17} /></div><strong>{value}</strong><p>{note}</p></article>; }
function Sparkline({ rows = [], field, label, unit = '' }) {
  const values = rows.map(row => ({ at: row.observedAt, value: row.process?.[field] })).filter(row => Number.isFinite(row.value));
  const max = Math.max(1, ...values.map(row => row.value)), min = Math.min(0, ...values.map(row => row.value));
  const path = values.map((row, index) => `${index ? 'L' : 'M'}${10 + index / Math.max(1, values.length - 1) * 580},${100 - (row.value - min) / (max - min) * 80}`).join(' ');
  return <div className="aw-chart"><div><span>{label}</span><strong>{values.length ? numeric(values.at(-1).value) : '—'}{values.length ? unit : ''}</strong></div>{values.length > 1 ? <svg viewBox="0 0 600 120" role="img" aria-label={`${label}, ${values.length} observations in the past hour`}><path d="M10,100 H590 M10,60 H590 M10,20 H590" stroke="rgba(255,255,255,.06)" fill="none" /><path d={path} stroke="#ff9b8e" strokeWidth="2" fill="none" vectorEffect="non-scaling-stroke" /></svg> : <p className="aw-chart-empty">The chart appears after two monitoring samples.</p>}<p>Past hour · {values.length} observations</p></div>;
}
export function AdminOverview({ system, operations, sections, onNavigate, canOperate, onRefresh }) {
  const [actionError, setActionError] = useState('');
  const alerts = system?.alerts || [];
  const acknowledge = async id => { setActionError(''); try { await api.post(`/v1/admin/alerts/${id}/acknowledge`); onRefresh(); } catch (error) { setActionError(error.response?.data?.message || 'Could not acknowledge this alert.'); } };
  if (!sections.includes('operations')) return <div className="aw-role-home"><p className="aw-eyebrow">Your workspace</p><h2>Start where you’re needed.</h2><p>Your role determines the records and actions you can open.</p><div className="aw-quick-links">{[['support', 'Support inbox', 'Read customer requests and account notes.'], ['payments', 'Payments & billing', 'Review payments, subscriptions and access.'], ['users', 'Accounts', 'Find a photographer and inspect their account.'], ['visitorTraffic', 'Visitors & traffic', 'See where visitors arrive and what they open.']].filter(([key]) => sections.includes(key)).map(([key, title, text]) => <button type="button" key={key} onClick={() => onNavigate(key)}><span>{title}<small>{text}</small></span><ArrowUpRight size={20} /></button>)}</div></div>;
  return <>
    <div className="aw-overview-top"><section className="aw-attention"><div className="aw-panel-title"><span className="aw-eyebrow">Needs attention</span><span className="aw-count">{system ? alerts.length : '—'}</span></div><h2>{!system ? 'Waiting for a current check.' : alerts.length ? 'Let’s take a closer look.' : 'No open monitoring alerts.'}</h2><p className="aw-description">{!system ? 'Service status will appear when the API responds.' : alerts.length ? 'These conditions persisted across repeated checks.' : 'This only covers connected checks. Review monitoring coverage below.'}</p><div className="aw-alert-list">{alerts.slice(0, 4).map(alert => <article key={alert._id}><TriangleAlert size={17} /><div><strong>{alert.title}</strong><span>{alert.severity} · first seen {checkedTime(alert.firstSeenAt)}</span></div>{alert.status === 'acknowledged' ? <span className="aw-ack"><Check size={13} />Acknowledged</span> : canOperate && <button type="button" onClick={() => acknowledge(alert._id)}>Acknowledge</button>}</article>)}</div>{actionError && <p role="alert" className="aw-inline-error">{actionError}</p>}<button type="button" className="aw-text-link" onClick={() => onNavigate('operations')}>Open operations<ArrowRight size={16} /></button></section>
    <section className="aw-live"><div className="aw-panel-title"><span className="aw-eyebrow">Active now</span><Activity size={17} /></div><strong className="aw-live-value">{numeric(system?.activity?.total)}</strong><h2>Visible browser sessions</h2><p>Seen in the last 90 seconds. One person can have more than one session.</p><div className="aw-live-split"><span><b>{numeric(system?.activity?.photographers)}</b>Signed in</span><span><b>{numeric(system?.activity?.visitors)}</b>Visitors</span></div><span className="aw-live-foot">Refreshes every 30 seconds while this page is visible</span></section></div>
    <div className="aw-stats-grid"><Stat icon={Users} label="Photographer accounts" value={numeric(operations?.metrics?.accounts?.total)} note={operations ? `${numeric(operations.metrics?.accounts?.newLast30Days)} joined in the past 30 days` : 'Account count unavailable'} /><Stat icon={Server} label="API failures · 5 min" value={system ? `${numeric(system.requests?.errorRate * 100)}%` : '—'} note={system ? `${numeric(system.requests?.errors)} failures / ${numeric(system.requests?.count)} requests on this instance` : 'Waiting for request telemetry'} /><Stat icon={CircleHelp} label="Unresolved server errors" value={numeric(system?.openIssues)} note="Grouped by error code and route" /></div>
    <div className="aw-section-label"><h2>Monitoring coverage</h2><button type="button" className="aw-text-link" onClick={() => onNavigate('operations')}>All signals<ArrowRight size={15} /></button></div><Coverage system={system} />
    <div className="aw-quick-links">{[['support', 'Help a photographer', 'Open the support inbox and account records.'], ['aiJobs', 'Check processing jobs', 'Inspect failures, retry work and review progress.']].filter(([key]) => sections.includes(key)).map(([key, title, text]) => <button type="button" key={key} onClick={() => onNavigate(key)}><span>{title}<small>{text}</small></span><ArrowUpRight size={20} /></button>)}</div>
  </>;
}
function Coverage({ system }) {
  const notifications = system?.notifications;
  const emailStatus = !notifications ? 'unknown' : notifications.configured ? 'configured' : 'unconfigured';
  let emailDetails = 'Waiting for the API to report email settings.';
  if (notifications) {
    emailDetails = notifications.configured ? 'Recipient and email provider configured' : 'Set an alert recipient and email provider';
    if (!notifications.configured && notifications.recipientConfigured && notifications.providerConfigured === false) emailDetails = 'Configure the email provider on the API.';
    if (!notifications.configured && notifications.providerConfigured && notifications.recipientConfigured === false) emailDetails = 'Save an alert recipient in Product analytics.';
  }
  return <div className="aw-coverage">
    {(system?.externalMonitor?.checks || [{ name: 'api' }, { name: 'website' }]).map(check => <article key={check.name}><Server size={18} /><div><h3>{check.name === 'api' ? 'API readiness' : 'Public website'}</h3><p>{check.checkedAt ? `Last external check ${checkedTime(check.checkedAt)}` : 'Independent monitor has not reported yet'}</p></div><State status={check.status} /></article>)}
    <article><Mail size={18} /><div><h3>Critical alert email</h3><p>{emailDetails}</p></div><State status={emailStatus} /></article>
  </div>;
}
export function AdminOperations({ system, operations, onRefresh, canOperate }) {
  const [error, setError] = useState('');
  const acknowledge = async id => { setError(''); try { await api.post(`/v1/admin/alerts/${id}/acknowledge`); onRefresh(); } catch (failure) { setError(failure.response?.data?.message || 'Could not acknowledge the alert.'); } };
  return <>{system?.alerts?.length > 0 && <section className="aw-attention" style={{ marginBottom: 24 }}><div className="aw-section-label" style={{ marginTop: 0 }}><h2>Current incidents</h2><span className="aw-muted">{system.alerts.length} need attention</span></div><div className="aw-alert-list">{system.alerts.map(alert => <article key={alert._id}><TriangleAlert size={17} /><div><strong>{alert.title}</strong><span>{alert.severity} · first seen {checkedTime(alert.firstSeenAt)} · notification {alert.notificationStatus}</span></div>{alert.status === 'acknowledged' ? <span className="aw-ack">Acknowledged</span> : canOperate && <button type="button" onClick={() => acknowledge(alert._id)}>Acknowledge</button>}</article>)}</div>{error && <p className="aw-inline-error" role="alert">{error}</p>}</section>}<Coverage system={system} /><div className="aw-section-label"><h2>API instance</h2><span className="aw-muted">{system?.revision ? `Release ${system.revision}` : 'Release ID unavailable'}</span></div><p className="aw-subnote">{system?.scope || 'Waiting for process telemetry.'} CPU is measured against one core. Memory limit is available on supported container hosts.</p><div className="aw-stats-grid"><Stat icon={Cpu} label="CPU" value={system ? `${numeric(system.process?.cpuPercent)}%` : '—'} note="Average since the previous sample" /><Stat icon={HardDrive} label="Memory in use" value={bytes(system?.process?.rssBytes)} note={system?.process?.memoryLimitBytes ? `Container limit ${bytes(system.process.memoryLimitBytes)}` : 'Container limit unavailable'} /><Stat icon={Clock3} label="Event loop · p95" value={system ? `${numeric(system.process?.eventLoopP95Ms)} ms` : '—'} note="Delay in processing queued callbacks" /></div><div className="aw-chart-grid"><Sparkline rows={system?.history} field="cpuPercent" label="CPU use" unit="%" /><Sparkline rows={system?.history} field="eventLoopP95Ms" label="Event-loop delay" unit=" ms" /></div>
    <div className="aw-section-label"><h2>Connected services</h2><span className="aw-muted">Configuration and observed health</span></div><div className="aw-services">{Object.entries(operations?.providers || {}).map(([key, service]) => <article key={key}><div><h3>{({ database: 'Database', r2: 'Photo storage', ai: 'Delivery AI', email: 'Email provider', paystack: 'Paystack' })[key]}</h3><State status={service.status} /></div><p>{service.message || service.reason || (service.status === 'healthy' ? 'The latest connection check passed.' : 'No check details available.')}</p>{service.latencyMs !== undefined && <small>{numeric(service.latencyMs)} ms · checked {checkedTime(operations.generatedAt)}</small>}{service.failuresLast24Hours !== undefined && <small>{numeric(service.failuresLast24Hours)} recorded failures in 24 hours</small>}</article>)}</div>
    <div className="aw-section-label"><h2>Background workers</h2></div><div className="aw-services">{(system?.workers || []).map(worker => <article key={worker.workerName}><div><h3>{worker.workerName}</h3><State status={worker.status} /></div><p>{worker.stage}</p><small>{checkedTime(worker.heartbeatAt)}</small></article>)}</div>
    <div className="aw-section-label"><h2>Routes to investigate</h2><span className="aw-muted">Past 5 minutes · approximate latency buckets</span></div><div className="aw-table-wrap"><table className="aw-table"><thead><tr><th>Route template</th><th>Requests</th><th>5xx</th><th>Average</th><th>p95 ≤</th></tr></thead><tbody>{(system?.requests?.routes || []).slice(0, 15).map(row => <tr key={row.route}><td><code>{row.route}</code></td><td>{numeric(row.count)}</td><td>{numeric(row.errors)}</td><td>{numeric(row.averageMs)} ms</td><td>{row.p95Ms >= 15000 ? '15,000+ ms' : `${numeric(row.p95Ms)} ms`}</td></tr>)}</tbody></table>{!system?.requests?.routes?.length && <p className="aw-empty">No observed customer requests in this window. Admin polling is excluded.</p>}</div>
    <p className="aw-subnote">Metrics are sampled every 30 seconds and retained for seven days. Server error groups expire after 90 days. Host restarts, OOM events and network outages still require the independent monitor and hosting logs.</p></>;
}
export function AdminIssues({ data, status, setStatus, onPage, loading, onRefresh, canOperate }) {
  const [selected, setSelected] = useState(null), [resolution, setResolution] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const update = async (item, nextStatus) => {
    setBusy(true); setError('');
    try { await api.patch(`/v1/admin/issues/${item._id}`, { status: nextStatus, resolution: nextStatus === 'resolved' ? resolution : '' }); setSelected(null); setResolution(''); onRefresh(); }
    catch (failure) { setError(failure.response?.data?.message || 'Could not update this issue.'); }
    finally { setBusy(false); }
  };
  return <><div className="aw-issue-toolbar"><div className="aw-segmented" aria-label="Issue status">{['open', 'acknowledged', 'resolved'].map(value => <button type="button" key={value} aria-pressed={value === status} onClick={() => { setStatus(value); setSelected(null); }}>{value}</button>)}</div><span className="aw-muted">{data ? `${numeric(data.total)} ${status} groups` : 'Waiting for error data'}</span></div>{error && <p role="alert" className="aw-inline-error">{error}</p>}<div className="aw-issues">{(data?.items || []).map(item => <article key={item._id}><div className="aw-issue-main"><div><span className="aw-error-code">{item.code}</span><h2>{item.route || 'Background process'}</h2><p>{numeric(item.occurrences)} sampled occurrences · last seen {checkedTime(item.lastSeenAt)}</p></div><span className="aw-issue-status">{item.status}</span></div>{item.frames?.length > 0 && <details><summary>Sanitized call stack</summary><pre>{item.frames.join('\n')}</pre></details>}{canOperate && item.status !== 'resolved' && <div className="aw-issue-actions">{item.status === 'open' && <button disabled={busy} type="button" onClick={() => update(item, 'acknowledged')}>Assign to me</button>}<button disabled={busy} type="button" onClick={() => { setSelected(selected === item._id ? null : item._id); setResolution(''); }}>Record a fix</button></div>}{selected === item._id && <form className="aw-resolution" onSubmit={event => { event.preventDefault(); update(item, 'resolved'); }}><label htmlFor={`fix-${item._id}`}>What fixed this error?</label><textarea id={`fix-${item._id}`} value={resolution} onChange={event => setResolution(event.target.value)} required minLength={5} maxLength={1000} autoFocus /><button type="submit" disabled={busy || resolution.trim().length < 5}>Mark resolved</button></form>}{item.resolution && item.status === 'resolved' && <p className="aw-resolution-note">{item.resolution}</p>}</article>)}</div>{data && !data.items.length && !loading && <div className="aw-empty-state"><Check size={24} /><h2>No {status} server errors.</h2><p>Captured 5xx responses and unhandled API errors appear here. A resolved error reopens if it happens again.</p></div>}{data?.pages > 1 && <p className="aw-subnote">Showing page {data.page} of {data.pages}. Narrow the status or use the API’s page parameter to inspect older groups.</p>}<div className="aw-section-label"><h2>Browser reports · 24 hours</h2></div><div className="aw-services">{(data?.browser || []).map(row => <article key={`${row.name}-${row.code}`}><h3>{row.code || row.name}</h3><p>{numeric(row.count)} reports · last seen {checkedTime(row.lastSeenAt)}</p></article>)}</div><p className="aw-subnote">Browser reports are grouped counters, without error messages, private photo URLs or session replay. They do not provide full crash traces.</p></>;
}
