import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Activity, ArrowUpRight, Check, ChevronDown, CircleHelp, Clock3, RefreshCw, TriangleAlert, Users } from 'lucide-react';
import api from '../services/api.js';
import './ProductInsights.css';

const number = value => value == null ? '—' : new Intl.NumberFormat('en-NG', { maximumFractionDigits: 1 }).format(value);
const date = value => value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(value)) : 'No observation';
const elapsed = value => value == null ? '—' : value < 60 ? `${Math.round(value)}s` : value < 3600 ? `${Math.round(value / 60)}m` : `${number(value / 3600)}h`;
const label = name => ({ 'account.activated': 'Account activated', 'upload.completed': 'Upload completed', 'upload.failed': 'Upload failed', 'delivery.publish.succeeded': 'Delivery published', 'delivery.publish.failed': 'Publishing failed', 'billing.checkout.started': 'Checkout opened', 'billing.payment.confirmed': 'Payment confirmed', 'javascript.error': 'Browser error' }[name] || String(name).replaceAll('.', ' ').replaceAll('_', ' '));
export function Diagnostic({ value }) {
  if (!value) return null;
  return <details className="pi-diagnostic"><summary><ChevronDown size={14} />Code locations · {value.release || 'unknown release'}</summary><p>{value.type} · {value.mechanism}</p>{value.frames?.length ? <pre>{value.frames.map(frame => frame.original ? `${frame.original.source}:${frame.original.line}:${frame.original.column} (${frame.asset}:${frame.line}:${frame.column})` : `${frame.asset}:${frame.line}:${frame.column}`).join('\n')}</pre> : <p>No application code location was available.</p>}<small>Error messages and page contents are excluded.</small></details>;
}
export function ActivityTimeline({ endpoint, onError }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [failures, setFailures] = useState(false), [refresh, setRefresh] = useState(0), [cursor, setCursor] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { setCursor(''); setData(null); }, [endpoint, failures, refresh]);
  useEffect(() => {
    if (!endpoint) return;
    const controller = new AbortController(); setBusy(true); setError('');
    api.get(endpoint, { params: { failures: String(failures), ...(cursor ? { before: cursor } : {}) }, signal: controller.signal }).then(response => {
      if (!controller.signal.aborted) setData(current => cursor && current ? { ...response.data.data, items: [...current.items, ...response.data.data.items] } : response.data.data);
    }).catch(failure => { if (!controller.signal.aborted) setError(failure.response?.data?.message || 'Activity could not load. Please retry.'); }).finally(() => { if (!controller.signal.aborted) setBusy(false); });
    return () => controller.abort();
  }, [endpoint, failures, refresh, cursor]);
  return <section className="pi-card pi-activity" aria-label="Account activity"><header className="pi-card-header"><div><p className="pi-kicker">Support investigation</p><h3>Recent account activity</h3></div><button className="pi-icon-button" type="button" aria-label="Refresh account activity" disabled={busy} onClick={() => setRefresh(value => value + 1)}><RefreshCw size={16} /></button></header>
    <div className="pi-segmented"><button type="button" aria-pressed={!failures} onClick={() => setFailures(false)}>All activity</button><button type="button" aria-pressed={failures} onClick={() => setFailures(true)}>Errors only</button></div>
    {error && <p className="pi-error" role="alert">{error}</p>}{busy && <p role="status" className="pi-note">Loading activity…</p>}
    {data?.note && <p className="pi-note">{data.note}</p>}
    <ol className="pi-timeline">{data?.items?.map(item => <li key={item.id}><span className={`pi-dot${item.status === 'failed' || item.diagnostic ? ' is-error' : ''}`} /><div><div className="pi-timeline-title"><strong>{item.diagnostic?.type || label(item.name)}</strong><time>{date(item.occurredAt)}</time></div><p>{item.source === 'server' ? 'Server recorded' : 'Browser reported'}{item.deviceType ? ` · ${item.deviceType}` : ''}{item.browser ? ` · ${item.browser}` : ''}{item.excluded ? ' · Excluded from reports' : ''}</p>{item.route && <code>{item.route}</code>}<Diagnostic value={item.diagnostic} />{onError && item.fingerprint && <button className="pi-text-button" onClick={() => onError(item.fingerprint)}>Inspect error group<ArrowUpRight size={14} /></button>}</div></li>)}</ol>
    {!busy && data && !data.items?.length && !data.note && <p className="pi-note">No {failures ? 'errors' : 'activity'} recorded for this account.</p>}{data?.next && <button className="pi-button" disabled={busy} onClick={() => setCursor(data.next)}>Load older activity</button>}
  </section>;
}
export function BrowserErrors({ onAccount, refreshKey = 0, fingerprint = '' }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [days, setDays] = useState(7), [refresh, setRefresh] = useState(0);
  useEffect(() => { const controller = new AbortController(); setError(''); api.get('/v1/admin/browser-errors', { params: { days, ...(fingerprint ? { fingerprint } : {}) }, signal: controller.signal }).then(response => { if (!controller.signal.aborted) setData(response.data.data); }).catch(failure => { if (!controller.signal.aborted) setError(failure.response?.data?.message || 'Browser errors could not load.'); }); return () => controller.abort(); }, [days, refresh, refreshKey, fingerprint]);
  return <motion.section className="pi-browser" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><header className="pi-card-header"><div><p className="pi-kicker">Client application</p><h2>Browser errors</h2><p className="pi-note">Grouped by error type and application code location. Counts cover the selected period.</p></div><div className="pi-actions"><label className="pi-sr-only" htmlFor="browser-days">Browser error period</label><select id="browser-days" value={days} onChange={event => setDays(Number(event.target.value))}>{[7, 30, 90].map(value => <option key={value} value={value}>Last {value} days</option>)}</select><button className="pi-icon-button" aria-label="Refresh browser errors" onClick={() => setRefresh(value => value + 1)}><RefreshCw size={16} /></button></div></header>
    {error && <p role="alert" className="pi-error">{error}</p>}{!data && !error && <p role="status">Loading browser reports…</p>}
    <div className="pi-error-grid">{data?.items?.map(item => <article className="pi-card" key={item.fingerprint} id={`browser-${item.fingerprint}`}><div className="pi-card-header"><h3><TriangleAlert size={18} />{item.diagnostic?.type || 'Browser exception'}</h3><span className="pi-count">{number(item.occurrences)} reports</span></div><code>{item.route}</code><div className="pi-error-numbers"><span><strong>{number(item.affectedAccounts)}</strong>accounts</span><span><strong>{number(item.affectedSessions)}</strong>sessions</span></div><p className="pi-note">First: {date(item.firstAt)}<br />Latest: {date(item.lastAt)}</p><p className="pi-note">Browsers: {item.browsers?.filter(Boolean).join(', ') || 'Unknown'}<br />Releases: {item.releases?.join(', ') || 'Unknown'}</p><Diagnostic value={item.diagnostic} />{onAccount && item.accountIds?.length > 0 && <details className="pi-diagnostic"><summary><Users size={14} />Affected accounts</summary><div className="pi-account-links">{item.accountIds.map((id, index) => <button className="pi-button" key={id} onClick={() => onAccount({ id })}>Open account {index + 1}<ArrowUpRight size={14} /></button>)}</div>{item.affectedAccounts > item.accountIds.length && <p className="pi-note">Showing the first {item.accountIds.length} accounts.</p>}</details>}</article>)}</div>
    {data && !data.items?.length && <div className="pi-empty"><Check size={24} /><h3>No detailed browser errors recorded.</h3><p>Reports begin with the updated client. Older generic counters remain above.</p></div>}
  </motion.section>;
}
function CohortAccounts({ cohort, days, onAccount }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [page, setPage] = useState(1);
  useEffect(() => { const controller = new AbortController(); setError(''); setData(null); api.get(`/v1/admin/product-cohorts/${cohort}`, { params: { days, page }, signal: controller.signal }).then(response => { if (!controller.signal.aborted) setData(response.data.data); }).catch(failure => { if (!controller.signal.aborted) setError(failure.response?.data?.message || 'Accounts could not load.'); }); return () => controller.abort(); }, [cohort, days, page]);
  return <div className="pi-cohort-accounts">{error && <p role="alert" className="pi-error">{error}</p>}{!data && !error && <p role="status">Loading accounts…</p>}{data?.items?.map(item => <button className="pi-button" key={item.id} onClick={() => onAccount(item)}>{item.name}<ArrowUpRight size={14} /></button>)}{data && !data.items?.length && <p>No matching accounts.</p>}<div className="pi-actions">{page > 1 && <button className="pi-button" onClick={() => setPage(value => value - 1)}>Previous</button>}{data?.more && <button className="pi-button" onClick={() => setPage(value => value + 1)}>Next accounts</button>}</div></div>;
}
function EventCatalogue({ days }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [search, setSearch] = useState('');
  useEffect(() => { const controller = new AbortController(); setError(''); setData(null); api.get('/v1/admin/product-analytics', { params: { days }, signal: controller.signal }).then(response => { if (!controller.signal.aborted) setData(response.data.data); }).catch(() => { if (!controller.signal.aborted) setError('Event counts could not load. Close and reopen to retry.'); }); return () => controller.abort(); }, [days]);
  return <div>{error && <p role="alert" className="pi-error">{error}</p>}{!data && !error && <p role="status">Loading event counts…</p>}{data && <><p className="pi-note">{number(data.totals?.events)} events · {number(data.totals?.uniqueSessions)} sessions · {number(data.totals?.failedEvents)} reported failures. Independent counts, separate from ordered funnels.</p><label className="pi-period">Find an event<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="For example: upload or assistant" /></label><div className="pi-catalogue">{data.eventCounts?.filter(item => item.name.includes(search.toLowerCase())).map(item => <div key={item.name}><span>{item.name}</span><strong>{number(item.events)}</strong></div>)}</div>{data.eventCounts?.length === 0 && <p className="pi-note">No events recorded in this period.</p>}</>}</div>;
}
export default function ProductInsights({ data, days, onDaysChange, error, onAccount }) {
  const [period, setPeriod] = useState(7), [cohort, setCohort] = useState('');
  const [catalogue, setCatalogue] = useState(false);
  const retention = data?.retention?.find(item => item.periodDays === period), integration = data?.integration;
  return <motion.div className="pi-workspace" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .3 }}>
    <section className="pi-intro"><div><p className="pi-kicker">Product analytics</p><h2>From signup<br /><em>to the next delivery.</em></h2><p>See where photographers get started, where they stop, and whether they come back.</p></div><label className="pi-period">Report period<select value={days} onChange={event => { setCohort(''); onDaysChange(Number(event.target.value)); }}>{[7, 30, 90].map(value => <option key={value} value={value}>Last {value} days</option>)}</select></label></section>
    {error && <p role="alert" className="pi-error">{error}</p>}{!data && !error && <p role="status">Loading product reports…</p>}
    {integration && <aside className="pi-integration"><Activity size={18} /><div><strong>{integration.status === 'disabled' ? 'PostHog is off' : integration.status === 'setup-needed' ? 'PostHog setup needed' : integration.lastAcceptedAt ? 'PostHog accepted an event batch' : 'PostHog configured · awaiting acceptance'}</strong><p>{integration.status === 'disabled' ? 'Veylo reports below use retained service events.' : `${number(integration.pending)} queued · ${number(integration.failed)} failed · last acceptance ${date(integration.lastAcceptedAt)}`}</p></div></aside>}
    <div className="pi-funnels">{data?.funnels?.map((funnel, index) => <section className={`pi-card pi-funnel pi-funnel-${index}`} key={funnel.key}><header><span className="pi-section-number">0{index + 1}</span><div><h3>{funnel.title}</h3><p>{funnel.identity === 'session' ? 'Distinct client sessions' : funnel.identity === 'checkout' ? 'Distinct checkout attempts' : 'Distinct photographers'} · {funnel.windowHours >= 24 ? `${funnel.windowHours / 24} ${funnel.windowHours === 24 ? 'day' : 'days'}` : `${funnel.windowHours * 60} minutes`} to finish</p></div></header><ol>{funnel.steps.map((step, stepIndex) => <li key={step.name}><div className="pi-step-title"><span><i>{["i", "ii", "iii", "iv"][stepIndex]}</i>{step.label}</span><strong>{number(step.reached)}</strong></div><div className="pi-track"><span style={{ width: `${step.rate || 0}%` }} /></div><div className="pi-step-detail"><span>{step.rate == null ? 'No starts yet' : `${number(step.rate)}% of starts`}</span>{stepIndex > 0 && <span>{number(step.pending)} pending · {number(step.dropped)} stopped</span>}</div>{stepIndex > 0 && step.reached > 0 && <p className="pi-note"><Clock3 size={12} />Median from start: {elapsed(step.medianSeconds)}</p>}</li>)}</ol></section>)}</div>
    <p className="pi-note"><CircleHelp size={15} />Steps must happen in order. Pending participants still have time to finish; stopped participants have passed the completion window.</p>
    <div className="pi-report-grid"><section className="pi-card pi-retention"><header className="pi-card-header"><div><p className="pi-kicker">Repeat use</p><h3>Do photographers return?</h3><p className="pi-note">Publishing again after their first recorded publication.</p></div><div className="pi-segmented">{[7, 30].map(value => <button key={value} aria-pressed={period === value} onClick={() => setPeriod(value)}>{value === 7 ? 'Weekly' : 'Monthly'}</button>)}</div></header><div className="pi-retention-rows">{retention?.rows?.slice(0, 12).map(row => <article key={row.date}><header><strong>{row.date}</strong><span>{number(row.size)} photographers</span></header><div className="pi-retention-cells">{row.periods.map(cell => <div key={cell.period} style={{ background: cell.rate == null ? undefined : `rgba(255,90,71,${.04 + cell.rate / 500})` }}><span>{period === 7 ? 'Week' : 'Month'} {cell.period}</span><strong>{cell.rate == null ? '—' : `${number(cell.rate)}%`}</strong><small>{cell.rate == null ? 'Not mature yet' : `${cell.returned} of ${cell.eligible}`}</small></div>)}</div></article>)}</div>{!retention?.rows?.length && <p className="pi-note">No publication cohorts in this period.</p>}<p className="pi-note">Only completed intervals are measured. Dates use Lagos time. A dash means there is not enough elapsed time.</p></section>
      <div className="pi-side-reports"><section className="pi-card"><p className="pi-kicker">People to understand</p><h3>Saved user groups</h3><div className="pi-cohorts">{data?.cohorts?.map(item => <div key={item.key}>{onAccount ? <button onClick={() => setCohort(cohort === item.key ? '' : item.key)} aria-expanded={cohort === item.key}><span>{item.label}</span><strong>{number(item.count)}<ArrowUpRight size={15} /></strong></button> : <p><span>{item.label}</span><strong>{number(item.count)}</strong></p>}{cohort === item.key && <CohortAccounts key={`${cohort}-${days}`} cohort={cohort} days={days} onAccount={onAccount} />}</div>)}</div></section><section className="pi-card"><p className="pi-kicker">Published work</p><h3>Formats photographers use</h3><div className="pi-formats">{data?.formats?.map(item => <div key={item.format}><span>{item.format.replaceAll('-', ' ')}</span><strong>{number(item.photographers)}</strong></div>)}</div>{!data?.formats?.length && <p className="pi-note">No recorded publications in this period.</p>}<p className="pi-note">Distinct photographers per format. One person can use several formats.</p></section></div></div>
    <details className="pi-card pi-diagnostic" onToggle={event => setCatalogue(event.currentTarget.open)}><summary><Activity size={16} />Event catalogue and counts</summary>{catalogue && <EventCatalogue days={days} />}</details>
    {data?.coverage && <footer className="pi-coverage"><CircleHelp size={18} /><p>{data.coverage.note}<br />Earliest retained event in this report: {date(data.coverage.firstRecordedAt)}. Refunded payments and subscription access remain in Payments &amp; billing.</p></footer>}
  </motion.div>;
}
