import React, { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Check, ClipboardList, CreditCard, FileCheck2, LoaderCircle, RefreshCw } from 'lucide-react';
import { motion } from 'framer-motion';
import api from '../services/api.js';
import { HelpNotice, helpDate, helpMoney } from './SupportWorkspace.jsx';
const reasons = { 'change-of-mind': 'First-payment change of mind', 'duplicate-charge': 'Duplicate charge', 'charged-after-cancellation': 'Charge after confirmed cancellation', 'paid-access-missing': 'Paid access not provided', 'service-failure': 'Material service failure', other: 'Other payment issue' };
export function RefundEvidence({ evidence }) {
  if (!evidence) return null;
  return <div className="ah-refund-evidence"><h3>Evidence for this paid period</h3><div className="ah-evidence-grid"><div><span>First payment</span><strong>{evidence.firstPayment ? 'Yes' : 'No'}</strong></div><div><span>Requested within seven days</span><strong>{evidence.withinSevenDays ? 'Yes' : 'No'}</strong></div><div><span>Delivery activity recorded</span><strong>{evidence.usageByKind?.delivery || 0}</strong></div><div><span>Storage activity recorded</span><strong>{evidence.usageByKind?.storage || 0}</strong></div><div><span>Portfolio activity recorded</span><strong>{evidence.usageByKind?.portfolio || 0}</strong></div><div><span>Existing service records</span><strong>{evidence.usageCounts?.deliveries || 0} deliveries · {evidence.usageCounts?.stories || 0} stories{evidence.usageCounts?.storage ? ' · storage' : ''}{evidence.usageCounts?.portfolio ? ' · Portfolio' : ''}</strong></div></div>
    <p className="ah-notice">{evidence.eligibleForChangeOfMind ? 'The recorded checks meet the routine first-payment conditions. A person must still review the evidence.' : 'The recorded checks do not meet the routine change-of-mind conditions. Payment errors and service failures can still qualify for review.'}</p><p>{evidence.coverageNote}</p><p>Period: {helpDate(evidence.period?.start)} — {helpDate(evidence.period?.end)}{evidence.period?.estimated ? ' (estimated end)' : ''}</p>
    {evidence.timeline?.length > 0 && <details><summary>View retained usage history ({evidence.usageCounts.recorded})</summary><ol className="ah-usage-timeline">{evidence.timeline.map(item => <li key={item.id}><span>{item.kind === 'delivery' ? 'Client delivery published' : item.kind === 'storage' ? 'Paid storage used' : 'Portfolio feature used'}</span><time>{helpDate(item.usedAt)}</time></li>)}</ol><p>These records remain available after the related work is deleted.{evidence.timelineTruncated ? ' Showing the first 100 records.' : ''}</p></details>}
  </div>;
}
export default function RefundWorkspace() {
  const [params, setParams] = useSearchParams(), selected = params.get('refundRequest') || '';
  const [data, setData] = useState(null), [detail, setDetail] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [status, setStatus] = useState('open'), [view, setView] = useState('requests'), [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ action: 'needs-information', note: '', customerNote: '', amount: '', cancelRenewal: false });
  const key = useRef(crypto.randomUUID()), lock = useRef(false), active = useRef(selected); active.current = selected;
  async function load(signal) { try { const response = await api.get('/v1/admin/refund-requests', { params: { status }, signal }); if (!signal?.aborted) { setData(response.data.data); setError(''); } } catch (error) { if (!signal?.aborted) setError(error.response?.data?.message || 'Refund requests could not load.'); } }
  async function read(signal) { if (!selected) return; try { const response = await api.get(`/v1/admin/refund-requests/${selected}`, { signal }); if (!signal?.aborted && active.current === selected) { setDetail(response.data.data); return response.data.data; } } catch (error) { if (!signal?.aborted) setError(error.response?.data?.message || 'Refund review could not load.'); } }
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); const timer = setInterval(() => { if (!document.hidden) void load(controller.signal); }, 30000); return () => { controller.abort(); clearInterval(timer); }; }, [status]);
  useEffect(() => { const controller = new AbortController(); setDetail(null); setNotice(''); key.current = crypto.randomUUID(); read(controller.signal).then(detail => { if (detail && !controller.signal.aborted) setForm({ action: 'needs-information', note: '', customerNote: '', amount: String((detail.payment.amountKobo - (detail.payment.refundedAmountKobo || 0)) / 100), cancelRenewal: false }); }); return () => controller.abort(); }, [selected]);
  const select = value => setParams(value ? { section: 'payments', refundRequest: value } : { section: 'payments' });
  const change = event => { setForm(current => ({ ...current, [event.target.name]: event.target.type === 'checkbox' ? event.target.checked : event.target.value })); key.current = crypto.randomUUID(); };
  async function decision(event) { event.preventDefault(); if (lock.current) return; if (form.action === 'approve' && !window.confirm(`Submit a ${helpMoney(Math.round(Number(form.amount) * 100))} refund for ${detail.payment.reference}?${form.cancelRenewal ? ' Also stop future renewals on this account.' : ' Renewal will remain separate.'}`)) return; lock.current = true; setBusy(true); try { const response = await api.post(`/v1/admin/refund-requests/${selected}/decision`, { action: form.action, note: form.note, customerNote: form.customerNote, requestKey: key.current, cancelRenewal: form.cancelRenewal, ...(form.action === 'approve' ? { amountKobo: Math.round(Number(form.amount) * 100) } : {}) }); setNotice(response.data.message); await read(); await load(); } catch (error) { setError(error.response?.data?.message || 'The decision could not be confirmed. Check this review before trying again.'); } finally { lock.current = false; setBusy(false); } }
  async function recovery(url, body = {}) { if (lock.current) return; lock.current = true; setBusy(true); try { const response = await api.post(url, body); setNotice(response.data.message); await load(); } catch (error) { setError(error.response?.data?.message || 'The recovery action could not complete.'); } finally { lock.current = false; setBusy(false); } }
  return <motion.section className="ah-workspace ah-finance" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .25 }}>
    <div className="ah-support-heading"><div><p className="ah-kicker"><FileCheck2 size={15} />Payment help</p><h2>Refunds and billing recovery.</h2><p>Review the request, check the evidence and explain the decision.</p></div><button className="ah-button" onClick={() => { void load(); void read(); }}><RefreshCw size={16} />Refresh</button></div>{error && <HelpNotice error>{error}</HelpNotice>}{notice && <HelpNotice>{notice}</HelpNotice>}
    {!selected ? <><div className="ah-view-tabs"><button aria-pressed={view === 'requests'} onClick={() => setView('requests')}><ClipboardList size={15} />Refund requests</button><button aria-pressed={view === 'recovery'} onClick={() => setView('recovery')}><CreditCard size={15} />Needs attention</button></div>{view === 'requests' ? <><label className="ah-filter-label">Review status<select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All reviews</option>{['open', 'needs-information', 'approved', 'declined'].map(value => <option value={value} key={value}>{value.replaceAll('-', ' ')}</option>)}</select></label><div className="ah-ticket-list">{data?.requests.map(request => <button key={request._id} onClick={() => select(request._id)}><FileCheck2 size={20} /><span className="ah-ticket-copy"><strong>{reasons[request.reason]}</strong><small>{request.userId?.name || 'Deleted account'} · {request.userId?.email || 'Restricted financial record'}</small><span>{request.ticketId?.ticketNumber} · Requested {helpDate(request.receivedAt)}</span></span><span className="ah-ticket-meta"><strong>{helpMoney(request.paymentId?.amountKobo)}</strong><small>{request.refundId?.status || request.status}</small></span><ArrowUpRight size={16} /></button>)}{data && !data.requests.length && <div className="ah-empty">No refund requests in this view.</div>}{data?.total > data.requests.length && <HelpNotice>Showing the oldest 100 of {data.total} requests. Narrow the status filter to review the queue.</HelpNotice>}</div></> : <div className="ah-recovery-grid">
      <section><h3>Refunds needing attention</h3>{data?.attention.map(item => <article key={item._id}><p><strong>{helpMoney(item.amountKobo)}</strong> · {item.status}</p><small>Updated {helpDate(item.updatedAt)}</small><button className="ah-button" disabled={busy} onClick={() => recovery(`/v1/admin/refunds/${item._id}/refresh`)}>Check Paystack<RefreshCw size={14} /></button>{item.status === 'needs-attention' && <p>The customer can submit bank details through the protected refund form in their support conversation.</p>}</article>)}{!data?.attention?.length && <p>No refunds need attention.</p>}</section>
      <section><h3>Billing events waiting or failed</h3>{data?.webhooks.map(item => <article key={item._id}><p>{item.eventType} · {item.status}</p><small>Received {helpDate(item.createdAt)} · {item.attempts} attempts</small><button className="ah-button" disabled={busy} onClick={() => recovery(`/v1/admin/billing/events/${item._id}/retry`)}>Retry event<RefreshCw size={14} /></button></article>)}{!data?.webhooks?.length && <p>No waiting or failed events.</p>}</section>
      <section><h3>Cancellation awaiting confirmation</h3>{data?.cancellations.map(item => <article key={item._id}><p>Requested {helpDate(item.cancelRequestedAt || item.cancelPendingAt)}</p><small>Paid access through {helpDate(item.paidThrough)}</small><button className="ah-button" disabled={busy} onClick={() => { const reason = window.prompt('Record why you are retrying cancellation:'); if (reason) recovery(`/v1/admin/users/${item.userId}/billing/cancel-renewal`, { reason }); }}>Confirm cancellation</button></article>)}{!data?.cancellations?.length && <p>No pending cancellations.</p>}</section>
      <section><h3>Confirmed payments without recorded access</h3>{data?.missingAccess.map(item => <article key={item._id}><p>{item.reference}</p><small>{helpMoney(item.amountKobo)} · {helpDate(item.paidAt)}</small><button className="ah-button" disabled={busy} onClick={() => recovery(`/v1/admin/users/${item.userId}/billing/verify-payment`, { reference: item.reference })}>Verify payment and access</button></article>)}{!data?.missingAccess?.length && <p>No unfulfilled payments recorded.</p>}</section>
      <section><h3>Disputed payments</h3>{data?.disputes.map(item => <article key={item._id}><p>{item.reference} · {helpMoney(item.amountKobo)}</p><small>{item.disputeResolvedAt ? `Resolved ${helpDate(item.disputeResolvedAt)}` : 'Review the dispute and submit evidence in Paystack.'}</small></article>)}{!data?.disputes?.length && <p>No disputed payments recorded.</p>}</section>
    </div>}</> : detail ? <div className="ah-refund-detail"><button className="ah-button" onClick={() => select('')}><ArrowLeft size={15} />All refund requests</button><header><p className="ah-kicker">{reasons[detail.request.reason]} · {detail.request.status}</p><h3>{detail.account?.name || 'Deleted account'}</h3><p>{detail.account?.email}</p><strong>{helpMoney(detail.payment.amountKobo)}</strong><p>{detail.payment.reference}</p><small>Requested {helpDate(detail.request.receivedAt)} · Policy {detail.request.policyVersion}</small></header><RefundEvidence evidence={detail.evidence} />
      <details className="ah-history"><summary>Payment and cancellation history</summary><h4>Payments</h4>{detail.payments.map(payment => <p key={payment._id}>{helpDate(payment.paidAt)} · {helpMoney(payment.amountKobo)} · {payment.status}<br />{payment.reference}{payment.fulfilledAt ? ' · Access recorded' : ' · No access fulfilment recorded'}</p>)}<h4>Subscriptions</h4>{detail.subscriptions.map(subscription => <p key={subscription._id}>{subscription.status} · Paid through {helpDate(subscription.paidThrough)}<br />Cancellation requested: {helpDate(subscription.cancelRequestedAt)}<br />Provider confirmed: {helpDate(subscription.providerCanceledAt)}{subscription.cancelPendingAt ? ' · Still awaiting confirmation' : ''}</p>)}</details>
      <HelpNotice>A full refund removes access funded by this payment. Newer valid paid access is preserved. A partial refund does not automatically end Pro. Stopping future renewal is separate.</HelpNotice>
      <button className="ah-button" onClick={() => setParams({ section: 'support', ticket: detail.request.ticketId })}>Open customer conversation<ArrowUpRight size={15} /></button>
      {detail.request.status === 'approved' ? <HelpNotice>Approved. Provider status: {detail.refunds.find(refund => String(refund._id) === String(detail.request.refundId))?.status || 'Check the refund record'}. Check the provider result before submitting anything else.</HelpNotice> : <form className="ah-decision" onSubmit={decision}><h3>Record the review</h3><label>Decision<select name="action" value={form.action} onChange={change}><option value="needs-information">Ask for more information</option><option value="decline">Decline the request</option><option value="approve">Approve a refund</option></select></label>{form.action === 'approve' && <><label>Refund amount (₦)<input type="number" name="amount" min="1" step=".01" max={(detail.payment.amountKobo - (detail.payment.refundedAmountKobo || 0)) / 100} value={form.amount} required onChange={change} /></label><label className="ah-check"><input type="checkbox" name="cancelRenewal" checked={form.cancelRenewal} onChange={change} />Also stop future renewals on this account</label></>}<label>Internal review note<textarea name="note" required minLength={10} maxLength={500} rows={3} value={form.note} onChange={change} placeholder="Explain what you checked and why this decision applies." /></label><label>Message to the customer<textarea name="customerNote" required minLength={10} maxLength={1000} rows={4} value={form.customerNote} onChange={change} placeholder="Explain the decision or the information you need." /></label><button className="ah-primary" disabled={busy}>{busy ? <LoaderCircle className="ah-spin" size={16} /> : <Check size={16} />}Save decision{form.action === 'approve' ? ' and request refund' : ''}</button></form>}
    </div> : !error && <div className="ah-empty">Opening refund evidence…</div>}
  </motion.section>;
}
