import React, { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Check, Clock3, Download, Inbox, LoaderCircle, LockKeyhole, Mail, MessageCircle, RefreshCw, Send, ShieldCheck } from 'lucide-react';
import { motion } from 'framer-motion';
import api from '../services/api.js';
import './SupportWorkspace.css';

export const helpDate = value => value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(value)) : '—';
export const helpMoney = value => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format((value || 0) / 100);
export function HelpNotice({ children, error }) { return <p className={`ah-notice${error ? ' is-error' : ''}`} role={error ? 'alert' : 'status'}>{children}</p>; }
const waiting = value => { const hours = Math.max(0, Math.floor((Date.now() - new Date(value)) / 3600000)); return hours < 1 ? 'Waiting less than an hour' : `Waiting ${hours}h`; };
export default function SupportWorkspace({ admin, search = '', onAccount, refreshKey = 0, onLoaded }) {
  const [params, setParams] = useSearchParams(), selected = params.get('ticket') || '';
  const [data, setData] = useState(null), [ticket, setTicket] = useState(null), [status, setStatus] = useState('open'), [mailbox, setMailbox] = useState('all'), [assigned, setAssigned] = useState('all'), [page, setPage] = useState(1);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [reply, setReply] = useState(''), [internal, setInternal] = useState(false);
  const key = useRef(crypto.randomUUID()), lock = useRef(false), active = useRef(selected); active.current = selected;
  const finance = ['superadmin', 'finance'].includes(admin.role);
  const select = value => setParams(value ? { section: 'support', ticket: value } : { section: 'support' });
  async function load(signal) {
    try { const response = await api.get('/v1/admin/support/tickets', { params: { search, status, mailbox, assigned, page }, signal }); if (!signal?.aborted) { setData(response.data.data); onLoaded?.(response.data.data.generatedAt || new Date().toISOString()); setError(''); } }
    catch (error) { if (!signal?.aborted) setError(error.response?.data?.message || 'Support inbox could not load.'); }
  }
  async function loadTicket(signal) {
    if (!selected) return;
    try { const response = await api.get(`/v1/admin/support/tickets/${selected}`, { signal }); if (!signal?.aborted && active.current === selected) setTicket(response.data.data); }
    catch (error) { if (!signal?.aborted) setError(error.response?.data?.message || 'Conversation could not load.'); }
  }
  useEffect(() => { setPage(1); }, [search]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); if (refreshKey) void loadTicket(controller.signal); const timer = setInterval(() => { if (!document.hidden) void load(controller.signal); }, 30000); return () => { controller.abort(); clearInterval(timer); }; }, [search, status, mailbox, assigned, page, refreshKey]);
  useEffect(() => { const controller = new AbortController(); setTicket(null); setReply(''); setNotice(''); key.current = crypto.randomUUID(); void loadTicket(controller.signal); const timer = setInterval(() => { if (!document.hidden) void loadTicket(controller.signal); }, 30000); return () => { controller.abort(); clearInterval(timer); }; }, [selected]);
  async function update(body) {
    if (lock.current) return; lock.current = true; setBusy(true); setError('');
    try { const response = await api.patch(`/v1/admin/support/tickets/${selected}`, body); setNotice(response.data.message); if (body.message) { setReply(''); key.current = crypto.randomUUID(); } await loadTicket(); await load(); }
    catch (error) { setError(error.response?.data?.message || 'The update could not be saved.'); }
    finally { lock.current = false; setBusy(false); }
  }
  async function retry(item) {
    const row = ticket.outbox.find(row => String(row.messageId) === String(item._id));
    const reason = window.prompt(row?.status === 'uncertain' ? 'Check the mailbox Sent folder first. If this email was NOT sent, record what you checked:' : 'Why should this email be retried?');
    if (!reason?.trim()) return;
    try { await api.post(`/v1/admin/support/tickets/${selected}/retry-email`, { messageId: item._id, reason, confirmedNotSent: row?.status === 'uncertain' }); setNotice('Email queued for another attempt.'); await loadTicket(); } catch (error) { setError(error.response?.data?.message || 'Email could not be retried.'); }
  }
  async function attachment(file) { try { const response = await api.get(`/v1/admin/support/tickets/${selected}/attachments/${file.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data), a = document.createElement('a'); a.href = url; a.download = file.name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch { setError('Screenshot could not be downloaded.'); } }
  async function linkRefund(event) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true);
    try { const response = await api.post(`/v1/admin/support/tickets/${selected}/refund-review`, { reference: form.get('reference'), reason: form.get('reason'), ownershipVerified: form.get('verified') === 'on', verificationNote: form.get('verificationNote') }); setParams({ section: 'payments', refundRequest: response.data.data.id }); }
    catch (error) { setError(error.response?.data?.message || 'Payment could not be linked.'); } finally { setBusy(false); }
  }
  async function moderate(event) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true);
    try { await api.post(`/v1/admin/support/tickets/${selected}/moderate`, { action: form.get('action'), targetType: form.get('targetType'), targetId: form.get('targetId'), reason: form.get('reason') }); setNotice('Moderation action recorded.'); await loadTicket(); }
    catch (error) { setError(error.response?.data?.message || 'Moderation action could not complete.'); } finally { setBusy(false); }
  }
  return <motion.div className="ah-workspace" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .25 }}>
    {error && <HelpNotice error>{error}</HelpNotice>}{notice && <HelpNotice>{notice}</HelpNotice>}
    <div className="ah-mail-health">{data?.mail?.mailboxes.map(item => <article key={item.mailbox}><Mail size={18} /><div><strong>{item.address}</strong><span>{item.status === 'not-configured' ? 'Connection setup needed' : item.status === 'connected' ? `Last sync ${helpDate(item.lastSuccessAt)}` : item.status.replaceAll('-', ' ')}{item.skippedCount > 0 ? ` · ${item.skippedCount} skipped; inspect webmail` : ''}</span></div><i className={item.status === 'connected' ? 'is-connected' : ''} /></article>)}<button className="ah-button" disabled={busy} onClick={async () => { setBusy(true); try { await api.post('/v1/admin/support/sync'); await load(); await loadTicket(); setNotice('Mailbox sync checked. Email accepted by a server is not proof of inbox delivery.'); } catch { setError('Mailbox sync could not complete.'); } finally { setBusy(false); } }}><RefreshCw size={16} />Sync mail</button></div>
    {!selected ? <><div className="ah-support-heading"><div><p className="ah-kicker">People waiting for help</p><h2>The support desk.</h2><p>Website messages, Assistant handoffs and connected email inboxes.</p></div><span>{data?.summary?.total || 0} matching requests</span></div>
      <div className="ah-filters"><label>Status<select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="all">All statuses</option>{['open', 'pending', 'resolved', 'closed'].map(value => <option key={value}>{value}</option>)}</select></label><label>Inbox<select value={mailbox} onChange={event => { setMailbox(event.target.value); setPage(1); }}><option value="all">All available inboxes</option>{admin.role !== 'finance' && <option value="general">General</option>}<option value="billing">Billing</option></select></label><label>Assigned to<select value={assigned} onChange={event => { setAssigned(event.target.value); setPage(1); }}><option value="all">Anyone</option><option value="mine">Me</option><option value="unassigned">Unassigned</option></select></label></div>
      <div className="ah-ticket-list">{data?.tickets.map(item => <button type="button" key={item.id} onClick={() => select(item.id)}><span className={`ah-ticket-icon${item.hasUnread ? ' has-unread' : ''}`}>{item.channel === 'email' ? <Mail size={19} /> : <MessageCircle size={19} />}</span><span className="ah-ticket-copy"><strong>{item.subject}</strong><small>{item.requester.name} · {item.requester.email}</small><span>{item.ticketNumber} · {item.mailbox} · {item.assignedAdmin?.name || 'Unassigned'}</span></span><span className="ah-ticket-meta"><em className={`is-${item.priority}`}>{item.priority}</em>{item.waitingSince && <small><Clock3 size={12} />{waiting(item.waitingSince)}</small>}</span><ArrowUpRight size={17} /></button>)}{data && !data.tickets.length && <div className="ah-empty"><Inbox size={30} /><h3>No matching messages.</h3><p>Try another status or inbox.</p></div>}{!data && !error && <div className="ah-empty">Loading support messages…</div>}</div>
      {data?.pages > 1 && <div className="ah-pagination"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)}>Previous</button><span>{page} / {data.pages}</span><button disabled={page >= data.pages} onClick={() => setPage(value => value + 1)}>Next</button></div>}
    </> : ticket ? <div className="ah-conversation"><div className="ah-thread-title"><button className="ah-button" onClick={() => select('')}><ArrowLeft size={15} />All requests</button><p className="ah-kicker">{ticket.ticketNumber} · {ticket.channel}</p><h2>{ticket.subject}</h2><p>{ticket.requester.name} · {ticket.requester.email}</p></div>
      <div className="ah-thread-layout"><section className="ah-thread-main"><div className="ah-messages">{ticket.messages.map(item => { const row = ticket.outbox?.find(row => String(row.messageId) === String(item._id)); return <article key={item._id} className={`${item.internal ? 'is-internal' : `is-${item.authorType}`}`}><header><strong>{item.internal ? <><LockKeyhole size={13} />Internal note</> : item.authorType === 'requester' ? ticket.requester.name : item.authorType === 'system' ? 'Veylo update' : 'Veylo team'}</strong><time>{helpDate(item.createdAt)}</time></header><p>{item.message}</p>{row && <footer><span>{row.status === 'sent' ? 'Accepted by email service' : `Email ${row.status}`}{row.sentCopyStatus === 'failed' ? ' · Sent-folder copy failed' : ''}</span>{['failed', 'uncertain'].includes(row.status) && <button onClick={() => retry(item)}>Review and retry</button>}</footer>}</article>; })}</div>
        {ticket.attachments?.length > 0 && <div className="ah-attachments">{ticket.attachments.map(file => <button className="ah-button" key={file.id} onClick={() => attachment(file)}><Download size={14} />{file.name}</button>)}</div>}
        <form className="ah-reply" onSubmit={event => { event.preventDefault(); update({ message: reply, internal, requestKey: key.current }); }}><label>{internal ? 'Private note for the team' : 'Reply to the customer'}<textarea required rows={5} maxLength={4000} value={reply} onChange={event => { setReply(event.target.value); key.current = crypto.randomUUID(); }} /></label><div><label className="ah-check"><input type="checkbox" checked={internal} onChange={event => setInternal(event.target.checked)} />Internal note</label><button className="ah-primary" disabled={busy || !reply.trim()}>{busy ? <LoaderCircle className="ah-spin" size={16} /> : internal ? <LockKeyhole size={16} /> : <Send size={16} />}{internal ? 'Save note' : 'Send reply'}</button></div><p>{internal ? 'Only administrators can see this note.' : 'The reply appears in the customer inbox and is queued for email.'}</p></form>
      </section><aside className="ah-thread-aside"><div className="ah-controls"><label>Status<select disabled={busy} value={ticket.status} onChange={event => update({ status: event.target.value })}>{['open', 'pending', 'resolved', 'closed'].map(value => <option key={value}>{value}</option>)}</select></label><label>Priority<select disabled={busy} value={ticket.priority} onChange={event => update({ priority: event.target.value })}>{['low', 'normal', 'high', 'urgent'].map(value => <option key={value}>{value}</option>)}</select></label><label>Owner<select disabled={busy} value={ticket.assignedAdmin?._id || ''} onChange={event => update({ assignedAdminId: event.target.value || null })}><option value="">Unassigned</option>{data?.administrators.map(person => <option key={person._id} value={person._id}>{person.name || person.username}</option>)}</select></label></div>
        <div className="ah-context"><p className="ah-kicker"><ShieldCheck size={14} />Support context</p>{ticket.context?.identity && <p>{ticket.context.identity}</p>}{ticket.context?.account && <p>Plan: {ticket.context.account.plan}<br />Paid through: {helpDate(ticket.context.account.paidThrough)}</p>}{ticket.context?.browser && <p>{ticket.context.browser.browser} · {ticket.context.browser.device}</p>}{ticket.context?.page && <><p>Page: {ticket.context.page.page}</p><ul>{Object.entries(ticket.context.page.workflow || {}).map(([key, value]) => <li key={key}>{key}: {String(value)}</li>)}</ul><ol>{ticket.context.page.recent?.slice(-5).map((event, index) => <li key={index}>{event.page} · {event.event.replaceAll('-', ' ')}</li>)}</ol></>}{ticket.context?.expected && <p><strong>Expected</strong><br />{ticket.context.expected}</p>}{ticket.context?.startedAt && <p>Started: {ticket.context.startedAt}</p>}{ticket.deliveryPublicId && <p>Delivery: {ticket.deliveryPublicId}</p>}{ticket.context?.paymentReference && <p>Payment: {ticket.context.paymentReference}<br />{ticket.context.paymentStatus}</p>}</div>
        {ticket.accountId && <button className="ah-button" onClick={() => onAccount?.(ticket.requester.email)}>Open customer account<ArrowUpRight size={15} /></button>}{finance && ticket.refundRequestId && <button className="ah-button" onClick={() => setParams({ section: 'payments', refundRequest: ticket.refundRequestId })}>Open refund review<ArrowUpRight size={15} /></button>}
        {finance && !ticket.refundRequestId && <details className="ah-admin-action"><summary>Link a refund request</summary><form onSubmit={linkRefund}><label>Payment reference<input name="reference" required maxLength={160} /></label><label>Review reason<select name="reason"><option value="change-of-mind">First-payment change of mind</option><option value="duplicate-charge">Duplicate charge</option><option value="charged-after-cancellation">Charge after confirmed cancellation</option><option value="paid-access-missing">Paid access not provided</option><option value="service-failure">Material service failure</option><option value="other">Other</option></select></label><label>How did you verify the account owner?<textarea name="verificationNote" required minLength={10} maxLength={500} rows={3} /></label><label className="ah-check"><input name="verified" type="checkbox" required />Account ownership verified</label><button className="ah-primary" disabled={busy}>Open review</button><p>The payment must belong to the requester’s account. The original received time is preserved.</p></form></details>}
        {admin.role !== 'finance' && <details className="ah-admin-action"><summary>Privacy and moderation</summary><form onSubmit={moderate}><label>Action<select name="action"><option value="abuse_review">Record abuse review</option><option value="copyright_hold">Record copyright hold</option><option value="takedown">Make reported work private</option><option value="restore">Restore reported work</option></select></label><label>Target<select name="targetType"><option value="delivery">Delivery</option><option value="portfolio">Portfolio</option><option value="account">Account</option></select></label><label>Target ID<input name="targetId" required defaultValue={ticket.deliveryPublicId || ticket.resourceId || ''} maxLength={160} /></label><label>Reason<textarea name="reason" required minLength={8} maxLength={1000} rows={3} /></label><button className="ah-button" disabled={busy}>Record action</button></form>{ticket.moderationActions?.map(action => <p key={action._id}>{action.action} · {helpDate(action.createdAt)}<br />{action.outcome}</p>)}</details>}
      </aside></div></div> : !error && <div className="ah-empty">Opening conversation…</div>}
  </motion.div>;
}
