import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Download, Inbox, LoaderCircle, MessageCircle, RefreshCw, Send } from 'lucide-react';
import api, { apiMessage } from '../services/api.js';
import { supportDate, supportMoney } from './SupportComposer.jsx';

export default function CustomerSupportInbox({ ticketId, onSelect, onNew }) {
  const [list, setList] = useState(null), [ticket, setTicket] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [reply, setReply] = useState('');
  const [banks, setBanks] = useState([]), [bank, setBank] = useState(''), [number, setNumber] = useState('');
  const key = useRef(crypto.randomUUID()), lock = useRef(false), active = useRef(ticketId); active.current = ticketId;
  const [uploading, setUploading] = useState(false);
  async function load(signal) {
    try { const response = await api.get(ticketId ? `/v1/support/tickets/${ticketId}` : '/v1/support/tickets', { signal }); if (signal?.aborted || active.current !== ticketId) return; ticketId ? setTicket(response.data.data) : setList(response.data.data); setError(''); }
    catch (error) { if (!signal?.aborted) setError(apiMessage(error, 'Your support inbox could not load.')); }
  }
  useEffect(() => { const controller = new AbortController(); setTicket(null); setReply(''); key.current = crypto.randomUUID(); void load(controller.signal); const timer = window.setInterval(() => { if (!document.hidden) void load(controller.signal); }, 30000); return () => { controller.abort(); clearInterval(timer); }; }, [ticketId]);
  const refund = ticket?.refundRequest?.refundId;
  useEffect(() => { if (refund?.status !== 'needs-attention') return; const controller = new AbortController(); api.get('/v1/support/refund-banks', { signal: controller.signal }).then(response => setBanks(response.data.data)).catch(() => { if (!controller.signal.aborted) setError('The bank list could not load. Please refresh to try again.'); }); return () => controller.abort(); }, [refund?.status]);
  async function send(event) { event.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); try { await api.post(`/v1/support/tickets/${ticketId}/messages`, { message: reply.trim(), requestKey: key.current }); setReply(''); key.current = crypto.randomUUID(); await load(); } catch (error) { setError(apiMessage(error)); } finally { setBusy(false); lock.current = false; } }
  async function download(attachment) { try { const response = await api.get(`/v1/support/tickets/${ticketId}/attachments/${attachment.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data), anchor = document.createElement('a'); anchor.href = url; anchor.download = attachment.name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch { setError('The screenshot could not be downloaded.'); } }
  async function addScreenshots(event) {
    const files = [...event.target.files].slice(0, 3); event.target.value = '';
    if (lock.current || !files.length) return;
    if (files.some(file => file.size > 4 * 1024 * 1024 || !['image/jpeg', 'image/png', 'image/webp'].includes(file.type))) { setError('Choose JPG, PNG or WebP files up to 4 MB each.'); return; }
    lock.current = true; setUploading(true); setError('');
    try { for (const file of files) { const body = new FormData(); body.append('screenshot', file); await api.post(`/v1/support/tickets/${ticketId}/attachments`, body); } await load(); }
    catch (error) { setError(apiMessage(error, 'A screenshot did not upload. Please try that file again.')); }
    finally { lock.current = false; setUploading(false); }
  }
  async function bankDetails(event) { event.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); try { await api.post(`/v1/support/refunds/${refund._id}/bank-details`, { accountNumber: number, bankId: bank }); setNumber(''); await load(); } catch (error) { setError(apiMessage(error)); } finally { setBusy(false); lock.current = false; } }
  return <div className="vs-inbox">{error && <p className="vs-error" role="alert">{error}<button type="button" onClick={() => load()}>Try again</button></p>}{ticketId ? ticket ? <>
    <header className="vs-thread-header"><button className="vs-secondary" type="button" onClick={() => onSelect('')}><ArrowLeft size={16} />All messages</button><div><p className="vs-kicker">{ticket.ticketNumber} · {ticket.status}</p><h2>{ticket.subject}</h2><p>Replies from the Veylo team appear here and are also sent by email.</p></div></header>
    {ticket.refundRequest && <div className="vs-refund-status"><strong>Refund review: {ticket.refundRequest.status.replaceAll('-', ' ')}</strong><span>Requested {supportDate(ticket.refundRequest.receivedAt)}</span>{refund && <p>{supportMoney(refund.amountKobo)} · {refund.status === 'processed' ? 'Processed by Paystack; your bank may still be completing the credit.' : refund.status.replaceAll('-', ' ')}</p>}</div>}
    <div className="vs-thread" aria-label="Support conversation">{ticket.messages.map(message => <article className={`vs-message is-${message.authorType}`} key={message.id}><header><strong>{message.authorType === 'requester' ? 'You' : message.authorType === 'system' ? 'Veylo update' : 'Veylo team'}</strong><time>{supportDate(message.createdAt)}</time></header><p>{message.message}</p></article>)}</div>
    {!!ticket.attachments?.length && <div className="vs-attachments">{ticket.attachments.map(attachment => <button type="button" key={attachment.id} onClick={() => download(attachment)}><Download size={16} />{attachment.name}</button>)}</div>}
    {(ticket.attachments?.length || 0) < 6 && <label className="vs-file"><Download size={18} /><span>{uploading ? 'Uploading screenshot…' : 'Add screenshots'}<small>JPG, PNG or WebP · up to 4 MB each · 6 per conversation</small></span><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy || uploading} onChange={addScreenshots} /></label>}
    {refund?.status === 'needs-attention' && <form className="vs-bank-form" onSubmit={bankDetails}><h3>Paystack needs your bank details.</h3><p>Use a bank account that belongs to you. These details go directly to the refund service and are not saved in this conversation.</p><label>Your bank<select required value={bank} onChange={event => setBank(event.target.value)}><option value="">Choose your bank</option>{banks.map(bank => <option key={bank.id} value={String(bank.id)}>{bank.name}</option>)}</select></label><label>Account number<input value={number} onChange={event => setNumber(event.target.value.replace(/\D/g, '').slice(0, 10))} required pattern="[0-9]{10}" inputMode="numeric" autoComplete="off" /></label><button className="vs-primary" disabled={busy}>Send securely</button></form>}
    <form className="vs-reply" onSubmit={send}><label htmlFor="support-reply">Reply to the team</label><textarea id="support-reply" required maxLength={4000} rows={4} value={reply} onChange={event => { setReply(event.target.value); key.current = crypto.randomUUID(); }} placeholder="Add an update or answer the team’s question." /><button className="vs-primary" disabled={busy || !reply.trim()}>{busy ? <LoaderCircle className="vs-spin" size={17} /> : <Send size={17} />}Send reply</button></form>
  </> : !error && <p className="vs-loading"><LoaderCircle className="vs-spin" size={20} />Opening conversation…</p> : <>
    <div className="vs-list-heading"><div><p className="vs-kicker">Your conversations</p><h2>Support inbox.</h2></div><button type="button" className="vs-secondary" onClick={() => load()} aria-label="Refresh support inbox"><RefreshCw size={17} /></button></div>
    {list?.tickets?.length ? <div className="vs-ticket-list">{list.tickets.map(item => <button type="button" key={item.id} onClick={() => onSelect(item.id)}><MessageCircle size={20} /><span><strong>{item.subject}{item.hasUnreadReply && <i aria-label="Unread reply" />}</strong><small>{item.ticketNumber} · {supportDate(item.updatedAt)}</small></span><em>{item.status}</em><ArrowUpRight size={18} /></button>)}{list.nextCursor && <button type="button" onClick={async () => { try { const response = await api.get('/v1/support/tickets', { params: { before: list.nextCursor } }); setList(current => ({ ...response.data.data, tickets: [...current.tickets, ...response.data.data.tickets] })); } catch (error) { setError(apiMessage(error)); } }}>Load older conversations</button>}</div> : list ? <div className="vs-empty"><Inbox size={34} /><h3>No support messages yet.</h3><p>When you message the team, you can follow the conversation here.</p><button className="vs-primary" onClick={onNew} type="button">Write a message<ArrowUpRight size={17} /></button></div> : !error && <p className="vs-loading">Loading your messages…</p>}
  </>}</div>;
}
